-- =============================================================================
-- Shefaa — full restore, in one paste.
--
-- Supabase Dashboard -> SQL Editor -> New query -> paste all of this -> Run.
--
-- GENERATED FILE — do not edit. Run ./scripts/build-restore.sh instead.
-- Sources:
--   supabase/migrations/*.sql   (in order)
--   supabase/seed.sql
--   ../Shefaa_Admin_Panel/supabase/migrations/002_fix_rls_policies.sql
--
-- Safe to re-run: every statement is if-not-exists / on-conflict-do-nothing.
-- Two manual steps follow at the bottom.
-- =============================================================================

-- ############## 1 of 3 — SCHEMA ##############

-- ---- 0000_base_schema.sql ----
-- =============================================================================
-- Shefaa — Base schema for the patient app.
--
-- IMPORTANT — HOW THIS FILE CAME TO BE
-- This schema was RECONSTRUCTED by reading the Dart data models in `lib/`
-- (the column names the app actually reads and writes) plus the additive
-- migrations in the admin-panel and doctor-dashboard repos. It was NOT dumped
-- from the live database, because the live schema had never been committed
-- anywhere.
--
-- Treat it as a starting point, not as the authority. As soon as you have a
-- working database again, replace this file with a real dump:
--
--     supabase db dump --db-url "$DB_URL" -f supabase/migrations/0000_base_schema.sql
--
-- Every statement is idempotent (`if not exists`), so running it against a
-- database that still has its tables will not destroy anything.
-- =============================================================================

create extension if not exists "pgcrypto";

-- -----------------------------------------------------------------------------
-- Location hierarchy: Governorate -> City -> Clinic
-- Quoted capitalised names match what the app and admin panel already query.
-- -----------------------------------------------------------------------------
create table if not exists public."Governorates" (
  id         bigint generated by default as identity primary key,
  name       text not null,
  created_at timestamptz not null default now()
);

create table if not exists public."Cities" (
  id             bigint generated by default as identity primary key,
  governorate_id bigint references public."Governorates" (id) on delete cascade,
  name           text not null,
  created_at     timestamptz not null default now()
);

create table if not exists public."Clinics" (
  id         bigint generated by default as identity primary key,
  city_id    bigint references public."Cities" (id) on delete cascade,
  name       text not null,
  address    text,
  created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Specialties — read by the app's home screen (HomeRemoteDatasource).
-- -----------------------------------------------------------------------------
create table if not exists public.specialties (
  id          bigint generated by default as identity primary key,
  name        text not null,
  icon        text,
  name_ar     text,
  description text,
  color       text,
  base_fee    numeric(10,2) default 0,
  created_at  timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Doctors — columns taken from DoctorModel.fromMap / toMap.
-- -----------------------------------------------------------------------------
create table if not exists public."Doctors" (
  id               bigint generated by default as identity primary key,
  name             text not null,
  title            text,
  specialization   text,
  specialty_id     bigint references public.specialties (id) on delete set null,
  clinic_id        bigint references public."Clinics" (id) on delete set null,
  image            text,
  location         text,
  rating           numeric(3,2) default 0 check (rating >= 0 and rating <= 5),
  consultation_fee numeric(10,2) not null default 0 check (consultation_fee >= 0),
  waiting_time     integer check (waiting_time >= 0),
  status           text not null default 'active',

  -- The other two apps depend on these: the admin panel writes email, and the
  -- doctor dashboard finds the signed-in doctor through user_id. Reconstructing
  -- this table from the Flutter models alone left them out.
  email            text,
  user_id          uuid references auth.users (id) on delete set null,
  phone            text,
  bio              text,
  license_number   text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create unique index if not exists doctors_user_id_key
  on public."Doctors" (user_id) where user_id is not null;
create unique index if not exists doctors_email_key
  on public."Doctors" (lower(email)) where email is not null;

create index if not exists doctors_specialty_idx on public."Doctors" (specialty_id);
create index if not exists doctors_clinic_idx    on public."Doctors" (clinic_id);

-- -----------------------------------------------------------------------------
-- Profiles — the patient record, keyed 1:1 to auth.users.
-- Written by AuthRemoteDataSource.register / read by ProfileRemoteDataSource.
-- -----------------------------------------------------------------------------
create table if not exists public.profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  name       text,
  phone      text,
  gender     text check (gender is null or gender in ('male', 'female')),
  birth_date date,
  status     text not null default 'active',
  created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Doctor availability — the bookable slots.
-- -----------------------------------------------------------------------------
create table if not exists public.doctor_availability (
  id         bigint generated by default as identity primary key,
  doctor_id  bigint not null references public."Doctors" (id) on delete cascade,
  date       date not null,
  start_time time not null,
  end_time   time not null,
  session    text not null check (session in ('morning', 'evening')),
  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  constraint doctor_availability_time_order check (end_time > start_time),
  -- A doctor cannot have the same slot listed twice.
  constraint doctor_availability_unique_slot unique (doctor_id, date, start_time)
);

create index if not exists doctor_availability_lookup_idx
  on public.doctor_availability (doctor_id, date, is_active);

-- -----------------------------------------------------------------------------
-- Payments — created alongside a booking.
-- -----------------------------------------------------------------------------
create table if not exists public.payments (
  id             bigint generated by default as identity primary key,
  patient_id     uuid references public.profiles (id) on delete set null,
  amount         numeric(10,2) not null check (amount >= 0),
  payment_method text not null check (payment_method in ('cash', 'instapay', 'card')),
  status         text not null default 'pending'
                   check (status in ('pending', 'paid', 'refunded', 'failed')),
  created_at     timestamptz not null default now()
);

create index if not exists payments_patient_idx on public.payments (patient_id);

-- -----------------------------------------------------------------------------
-- Bookings — the appointment itself.
-- -----------------------------------------------------------------------------
create table if not exists public.bookings (
  id          bigint generated by default as identity primary key,
  patient_id  uuid not null references public.profiles (id) on delete cascade,
  doctor_id   bigint not null references public."Doctors" (id) on delete cascade,
  payment_id  bigint references public.payments (id) on delete set null,
  booked_date date not null,
  start_time  time not null,
  end_time    time not null,
  -- 'no_show' matters for revenue: a patient who books and never arrives must be
  -- distinguishable from one who attended, or commission cannot be computed later.
  -- The doctor dashboard already sends this value (appointment.labels.ts).
  status      text not null default 'pending'
                check (status in ('pending', 'confirmed', 'completed', 'cancelled', 'no_show')),
  created_at  timestamptz not null default now()
);

create index if not exists bookings_patient_idx on public.bookings (patient_id);
create index if not exists bookings_doctor_idx  on public.bookings (doctor_id, booked_date);
create index if not exists bookings_status_idx  on public.bookings (status);

-- A doctor cannot be double-booked for the same slot. Cancelled bookings are
-- excluded so a cancelled slot can be rebooked.
create unique index if not exists bookings_no_double_booking
  on public.bookings (doctor_id, booked_date, start_time)
  where status <> 'cancelled';

-- -----------------------------------------------------------------------------
-- Admins — membership in this table is what grants admin-panel access.
-- Referenced by the is_admin() helper used in the RLS policies.
-- -----------------------------------------------------------------------------
create table if not exists public.admins (
  id         uuid primary key references auth.users (id) on delete cascade,
  name       text,
  created_at timestamptz not null default now()
);

-- Admin status comes from membership in public.admins and nothing else.
-- SECURITY DEFINER so the lookup is not itself filtered by admins' own RLS.
-- Defined here, with the table, because migrations that add policies depend on
-- it -- 0004 referenced it before the RLS migration had created it.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where id = auth.uid());
$$;

-- -----------------------------------------------------------------------------
-- Keep a profile row in step with every auth user, so a signup can never end up
-- with an auth account but no profile (the app currently inserts the profile
-- client-side, which silently fails when email confirmation is on).
-- -----------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- -----------------------------------------------------------------------------
-- Table privileges for the Supabase roles.
--
-- RLS decides which rows a role sees; GRANT decides whether it may read the
-- table at all. Without this every app query fails with 42501, whatever the
-- policies say. Not `grant all`: that includes TRUNCATE, which ignores RLS.
-- -----------------------------------------------------------------------------
grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant select on all tables in schema public to anon;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

alter default privileges in schema public
  grant select, insert, update, delete on tables to authenticated;
alter default privileges in schema public
  grant select on tables to anon;
alter default privileges in schema public
  grant all on tables to service_role;
alter default privileges in schema public
  grant usage, select on sequences to anon, authenticated, service_role;

-- ---- 0002_allow_no_show_status.sql ----
-- =============================================================================
-- Allow 'no_show' on bookings.status.
--
-- The doctor dashboard offers "No show" as a status (its appointment.labels.ts
-- lists it alongside completed/cancelled) and calls updateStatus with it, but
-- the CHECK constraint in 0000_base_schema.sql did not permit the value, so the
-- action would have failed against the database with a constraint violation.
--
-- The distinction also matters for revenue: commission is owed on a visit that
-- happened, and a booking the patient never showed up for is not that. Without
-- a separate value both collapse into 'cancelled' and the history needed to
-- bill a clinic later is lost.
--
-- Run this only if you already applied 0000_base_schema.sql. Fresh installs
-- pick the value up from the corrected 0000.
-- =============================================================================

alter table public.bookings drop constraint if exists bookings_status_check;

alter table public.bookings add constraint bookings_status_check
  check (status in ('pending', 'confirmed', 'completed', 'cancelled', 'no_show'));

-- ---- 0003_grant_table_privileges.sql ----
-- =============================================================================
-- Grant table privileges to the Supabase roles.
--
-- PostgreSQL checks permissions in two layers:
--
--   1. GRANT       — may this role touch the table at all?
--   2. RLS policy  — which rows may it see or change?
--
-- 0000_base_schema.sql and 002_fix_rls_policies.sql set up layer 2 and left
-- layer 1 entirely to Supabase's default privileges. When those defaults do
-- not apply -- as happened here after the tables were dropped and recreated --
-- every query from the app fails with:
--
--   PostgrestException(message: permission denied for table specialties,
--                      code: 42501)
--
-- Note the difference in symptom: a row blocked by RLS comes back as an empty
-- result, never as an error. A 42501 is always a missing GRANT.
--
-- Safe to re-run.
-- =============================================================================

grant usage on schema public to anon, authenticated, service_role;

-- SELECT/INSERT/UPDATE/DELETE only -- deliberately NOT `grant all`, which
-- would include TRUNCATE. TRUNCATE is not subject to row level security, so
-- granting it would let any signed-in patient empty a table outright no matter
-- what the policies say.
grant select, insert, update, delete
  on all tables in schema public
  to authenticated;

grant select on all tables in schema public to anon;

-- Identity columns do not need this, but any serial column added later would.
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

-- service_role runs behind the API and bypasses RLS by design; it is the role
-- an Edge Function uses to create a booking and its payment server-side.
grant all on all tables in schema public to service_role;

-- The same, for tables added from here on, so a new table is never invisible
-- to the app for this reason again.
alter default privileges in schema public
  grant select, insert, update, delete on tables to authenticated;

alter default privileges in schema public
  grant select on tables to anon;

alter default privileges in schema public
  grant all on tables to service_role;

alter default privileges in schema public
  grant usage, select on sequences to anon, authenticated, service_role;

-- ---- 0004_doctor_schedule.sql ----
-- =============================================================================
-- Weekly schedules, replacing the per-date availability rows.
--
-- doctor_availability stored one row per concrete date and time, so somebody
-- had to keep inserting rows forever. The seed generated 14 days; on day 15
-- every doctor would have shown no availability and the app would have said
-- "no slots" as though that were normal.
--
-- A doctor's working week is a pattern, so it is stored as one. Availability
-- for any date is computed from that pattern, which means it never expires and
-- changing the pattern needs no regeneration.
--
-- doctor_availability is NOT dropped here: the app still reads it. It goes when
-- the screens move over.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- The weekly pattern. 2-6 rows per doctor instead of thousands.
-- -----------------------------------------------------------------------------
create table if not exists public.doctor_schedule (
  id         bigint generated by default as identity primary key,
  doctor_id  bigint not null references public."Doctors" (id) on delete cascade,
  weekday    smallint not null check (weekday between 0 and 6),  -- 0 = Sunday, matching extract(dow)
  session    text not null check (session in ('morning', 'evening')),
  start_time time not null,
  end_time   time not null,

  -- How many patients the doctor takes in this session. Entered directly
  -- rather than derived from an average visit length: a dentist whose list
  -- mixes a 10-minute check with a 45-minute scaling knows their own number,
  -- and any average we computed would be worse than their estimate.
  capacity   integer not null check (capacity > 0),

  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint doctor_schedule_time_order check (end_time > start_time),
  unique (doctor_id, weekday, session)
);

create index if not exists doctor_schedule_lookup_idx
  on public.doctor_schedule (doctor_id, weekday) where is_active;

-- -----------------------------------------------------------------------------
-- Exceptions: a holiday, or one day that runs differently.
--
-- session null  -> the whole day
-- is_closed     -> no clinic
-- capacity/times-> override just those, keeping the rest of the pattern
--
-- Known limit (accepted for v1): an exception adjusts a session the weekly
-- pattern already has. It cannot add a session on a weekday the doctor does
-- not normally work -- to open an extra Friday clinic, add Friday to the
-- pattern and remove it afterwards.
-- -----------------------------------------------------------------------------
create table if not exists public.doctor_schedule_exceptions (
  id         bigint generated by default as identity primary key,
  doctor_id  bigint not null references public."Doctors" (id) on delete cascade,
  date       date not null,
  session    text check (session in ('morning', 'evening')),
  is_closed  boolean not null default true,
  start_time time,
  end_time   time,
  capacity   integer check (capacity > 0),
  reason     text,
  created_at timestamptz not null default now(),
  constraint doctor_exception_time_order
    check (start_time is null or end_time is null or end_time > start_time),
  unique (doctor_id, date, session)
);

create index if not exists doctor_schedule_exceptions_lookup_idx
  on public.doctor_schedule_exceptions (doctor_id, date);

-- -----------------------------------------------------------------------------
-- bookings: a booking now belongs to a session, not to a 30-minute slot.
--
-- start_time/end_time are kept as a snapshot of the session window at the time
-- of booking, so a later change to the schedule does not rewrite history.
-- -----------------------------------------------------------------------------
alter table public.bookings
  add column if not exists session text
    check (session is null or session in ('morning', 'evening'));

-- The old index assumed one patient per (doctor, date, start_time). Under the
-- queue model everyone in a session shares the same window, so it would reject
-- the second booking of every session.
drop index if exists public.bookings_no_double_booking;

-- What actually needs preventing now: the same patient taking two places in
-- one session. Capacity is enforced when booking, against doctor_sessions_on.
create unique index if not exists bookings_one_place_per_session
  on public.bookings (doctor_id, patient_id, booked_date, session)
  where status <> 'cancelled';

create index if not exists bookings_session_queue_idx
  on public.bookings (doctor_id, booked_date, session, created_at)
  where status <> 'cancelled';

-- -----------------------------------------------------------------------------
-- What is available for one doctor on one date, after exceptions and bookings.
-- -----------------------------------------------------------------------------
create or replace function public.doctor_sessions_on(p_doctor bigint, p_date date)
returns table (
  session    text,
  start_time time,
  end_time   time,
  capacity   integer,
  booked     bigint,
  remaining  integer
)
language sql
stable
security invoker
set search_path = public
as $$
  with base as (
    select s.session, s.start_time, s.end_time, s.capacity
    from public.doctor_schedule s
    where s.doctor_id = p_doctor
      and s.weekday = extract(dow from p_date)::smallint
      and s.is_active
  ),
  applied as (
    select
      b.session,
      coalesce(ex.start_time, b.start_time) as start_time,
      coalesce(ex.end_time,   b.end_time)   as end_time,
      coalesce(ex.capacity,   b.capacity)   as capacity,
      -- a whole-day exception wins over a per-session one
      coalesce(day_ex.is_closed, ex.is_closed, false) as closed
    from base b
    left join public.doctor_schedule_exceptions ex
      on ex.doctor_id = p_doctor and ex.date = p_date and ex.session = b.session
    left join public.doctor_schedule_exceptions day_ex
      on day_ex.doctor_id = p_doctor and day_ex.date = p_date and day_ex.session is null
  )
  select
    a.session, a.start_time, a.end_time, a.capacity,
    count(bk.id) as booked,
    greatest(a.capacity - count(bk.id), 0)::integer as remaining
  from applied a
  left join public.bookings bk
    on  bk.doctor_id   = p_doctor
    and bk.booked_date = p_date
    and bk.session     = a.session
    and bk.status <> 'cancelled'
  where not a.closed
  group by a.session, a.start_time, a.end_time, a.capacity
  order by a.start_time;
$$;

-- -----------------------------------------------------------------------------
-- Queue position, computed rather than stored.
--
-- Stored numbers would need rewriting for everyone behind a cancellation, and
-- would race when two patients book at the same moment. Computed, a cancelled
-- booking simply drops out and the numbers behind it close up -- which is the
-- promise the patient is shown: your number can improve, never get worse.
-- -----------------------------------------------------------------------------
create or replace view public.booking_queue as
  select
    b.id as booking_id,
    b.doctor_id,
    b.patient_id,
    b.booked_date,
    b.session,
    b.status,
    row_number() over (
      partition by b.doctor_id, b.booked_date, b.session
      order by b.created_at, b.id
    )::integer as queue_number
  from public.bookings b
  where b.status <> 'cancelled';

-- -----------------------------------------------------------------------------
-- Row level security and grants.
--
-- Both, deliberately: policies without grants produce 42501 and are
-- unreachable, which is exactly how the last round broke.
-- -----------------------------------------------------------------------------
alter table public.doctor_schedule            enable row level security;
alter table public.doctor_schedule_exceptions enable row level security;

do $$
declare tbl text;
begin
  foreach tbl in array array['doctor_schedule', 'doctor_schedule_exceptions']
  loop
    -- every signed-in user may read: this is what the app shows as availability
    execute format('drop policy if exists sched_read_all on public.%I;', tbl);
    execute format(
      'create policy sched_read_all on public.%I
         for select to authenticated using (true);', tbl);

    -- only an admin may write, until doctors have accounts of their own;
    -- a doctor-owns-their-schedule policy lands with doctor login
    execute format('drop policy if exists sched_admin_write on public.%I;', tbl);
    execute format(
      'create policy sched_admin_write on public.%I
         for all to authenticated
         using (public.is_admin()) with check (public.is_admin());', tbl);
  end loop;
end $$;

grant select, insert, update, delete
  on public.doctor_schedule, public.doctor_schedule_exceptions
  to authenticated;
grant select on public.doctor_schedule, public.doctor_schedule_exceptions to anon;
grant all on public.doctor_schedule, public.doctor_schedule_exceptions to service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

grant select on public.booking_queue to authenticated, anon, service_role;

revoke execute on function public.doctor_sessions_on(bigint, date) from public;
grant execute on function public.doctor_sessions_on(bigint, date)
  to anon, authenticated, service_role;

-- ---- 0005_doctor_accounts.sql ----
-- =============================================================================
-- Doctor logins: link a Doctors row to an auth account.
--
-- Nothing connected the three apps. The admin panel writes Doctors.email; the
-- doctor dashboard identifies a doctor through Doctors.user_id; the base schema
-- had neither column, so the admin panel's save would fail on an unknown column
-- and no doctor could ever sign in. Without that link the weekly schedule from
-- 0004 has nobody to edit it.
--
-- The link is made by matching a CONFIRMED email, in both directions, so it
-- works whichever happens first: the admin adding the doctor, or the doctor
-- signing up.
--
-- ############ READ THIS ############
-- The security of this rests on email confirmation being ON
-- (Authentication -> Providers -> Email -> Confirm email). With it off,
-- Supabase confirms every signup immediately, and anyone who knows a doctor's
-- email address could sign up with it and take over that doctor's dashboard.
-- Turn it on before any real doctor is added.
-- ###################################
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Columns the other two apps rely on, missing from the reconstructed schema.
-- -----------------------------------------------------------------------------
alter table public."Doctors" add column if not exists email          text;
alter table public."Doctors" add column if not exists user_id        uuid;
alter table public."Doctors" add column if not exists phone          text;
alter table public."Doctors" add column if not exists bio            text;
alter table public."Doctors" add column if not exists license_number text;
alter table public."Doctors" add column if not exists updated_at     timestamptz not null default now();

do $$ begin
  alter table public."Doctors"
    add constraint doctors_user_id_fkey
    foreign key (user_id) references auth.users (id) on delete set null;
exception when duplicate_object then null; end $$;

-- One auth account is one doctor.
create unique index if not exists doctors_user_id_key
  on public."Doctors" (user_id) where user_id is not null;

-- Two doctors cannot claim the same address, or a match would be ambiguous.
create unique index if not exists doctors_email_key
  on public."Doctors" (lower(email)) where email is not null;

-- -----------------------------------------------------------------------------
-- 2. Which doctor is signed in. The dashboard's RLS is built on this.
-- -----------------------------------------------------------------------------
create or replace function public.current_doctor_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select id from public."Doctors" where user_id = auth.uid() limit 1;
$$;

revoke execute on function public.current_doctor_id() from public;
grant execute on function public.current_doctor_id() to authenticated, service_role;

-- -----------------------------------------------------------------------------
-- 3. The link itself.
--
-- Claims only a doctor row that is still unclaimed, and only from an account
-- whose address is confirmed. Both conditions matter: the first stops a second
-- account stealing a linked doctor, the second is what makes "owns the address"
-- mean anything.
-- -----------------------------------------------------------------------------
create or replace function public.link_doctor_account(p_user_id uuid, p_email text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_doctor_id bigint;
begin
  if p_user_id is null or p_email is null or p_email = '' then
    return null;
  end if;

  update public."Doctors"
     set user_id = p_user_id,
         updated_at = now()
   where lower(email) = lower(p_email)
     and user_id is null
  returning id into v_doctor_id;

  return v_doctor_id;
end;
$$;

-- Direction A: the doctor signs up (or confirms) after the admin added them.
create or replace function public.on_auth_user_confirmed()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.email_confirmed_at is not null then
    perform public.link_doctor_account(new.id, new.email);
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_confirmed_link_doctor on auth.users;
create trigger on_auth_user_confirmed_link_doctor
  after insert or update of email_confirmed_at on auth.users
  for each row execute function public.on_auth_user_confirmed();

-- Direction B: the admin adds the doctor after they already have an account.
create or replace function public.on_doctor_email_set()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
begin
  if new.email is null or new.user_id is not null then
    return new;
  end if;

  select u.id into v_user_id
    from auth.users u
   where lower(u.email) = lower(new.email)
     and u.email_confirmed_at is not null
   limit 1;

  if v_user_id is not null
     and not exists (select 1 from public."Doctors" d where d.user_id = v_user_id) then
    new.user_id := v_user_id;
  end if;

  return new;
end;
$$;

drop trigger if exists on_doctor_email_set_link_account on public."Doctors";
create trigger on_doctor_email_set_link_account
  before insert or update of email on public."Doctors"
  for each row execute function public.on_doctor_email_set();

-- -----------------------------------------------------------------------------
-- 4. A linked doctor owns their own schedule.
--
-- 0004 left writing to admins only, because there was no way to be a doctor.
-- There is now, so add the doctor's own access beside it. Policies are OR-ed,
-- so this widens write access to exactly "the admin, or this doctor".
-- -----------------------------------------------------------------------------
do $$
declare tbl text;
begin
  foreach tbl in array array['doctor_schedule', 'doctor_schedule_exceptions']
  loop
    execute format('drop policy if exists sched_doctor_write on public.%I;', tbl);
    execute format(
      'create policy sched_doctor_write on public.%I
         for all to authenticated
         using (doctor_id = public.current_doctor_id())
         with check (doctor_id = public.current_doctor_id());', tbl);
  end loop;
end $$;

-- A doctor may edit their own row, but not create or delete doctors, and not
-- reassign the row to another account.
drop policy if exists doctors_self_update on public."Doctors";
create policy doctors_self_update on public."Doctors"
  for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ---- 0006_queue_counts_see_all_bookings.sql ----
-- =============================================================================
-- Queue numbers and remaining places were computed under the caller's own RLS.
--
-- doctor_sessions_on was declared `security invoker`, so its
--
--     count(bk.id) ... from public.bookings bk
--
-- ran under the caller's policies -- and bookings_select_own limits a patient to
-- `patient_id = auth.uid()`. The count it needs is precisely the one RLS hides.
--
-- Measured on a session that really held 2 bookings:
--
--     patient who already booked   -> booked = 1, remaining = 9
--     patient about to book        -> booked = 0, remaining = 10
--
-- So every patient was told "دورك رقم ١" however full the session was, and
-- `remaining` never reached zero, so a full session never showed as full.
--
-- The fix is `security definer`. It is the right tool here and not a hole: the
-- function returns aggregates only -- session, times, capacity, a count -- and
-- never a row that identifies a patient. search_path is pinned, as it must be.
--
-- NOTE this does not stop two patients racing for the last place; the capacity
-- check is still advisory, enforced by the UI. A database-level guard is a
-- separate change.
-- =============================================================================

create or replace function public.doctor_sessions_on(p_doctor bigint, p_date date)
returns table (
  session    text,
  start_time time,
  end_time   time,
  capacity   integer,
  booked     bigint,
  remaining  integer
)
language sql
stable
-- definer, not invoker: counting how full a session is means counting other
-- people's bookings, which the caller's own policies hide from them.
security definer
set search_path = public
as $$
  with base as (
    select s.session, s.start_time, s.end_time, s.capacity
    from public.doctor_schedule s
    where s.doctor_id = p_doctor
      and s.weekday = extract(dow from p_date)::smallint
      and s.is_active
  ),
  applied as (
    select
      b.session,
      coalesce(ex.start_time, b.start_time) as start_time,
      coalesce(ex.end_time,   b.end_time)   as end_time,
      coalesce(ex.capacity,   b.capacity)   as capacity,
      -- a whole-day exception wins over a per-session one
      coalesce(day_ex.is_closed, ex.is_closed, false) as closed
    from base b
    left join public.doctor_schedule_exceptions ex
      on ex.doctor_id = p_doctor and ex.date = p_date and ex.session = b.session
    left join public.doctor_schedule_exceptions day_ex
      on day_ex.doctor_id = p_doctor and day_ex.date = p_date and day_ex.session is null
  )
  select
    a.session, a.start_time, a.end_time, a.capacity,
    count(bk.id) as booked,
    greatest(a.capacity - count(bk.id), 0)::integer as remaining
  from applied a
  left join public.bookings bk
    on  bk.doctor_id   = p_doctor
    and bk.booked_date = p_date
    and bk.session     = a.session
    and bk.status <> 'cancelled'
  where not a.closed
  group by a.session, a.start_time, a.end_time, a.capacity
  order by a.start_time;
$$;

revoke execute on function public.doctor_sessions_on(bigint, date) from public;
grant execute on function public.doctor_sessions_on(bigint, date)
  to anon, authenticated, service_role;

-- -----------------------------------------------------------------------------
-- booking_queue: right numbers, but it was handing them out for every booking.
--
-- The view is `security_invoker = false` (the default), so it runs as its owner
-- and computes row_number() over every booking -- which is what makes the queue
-- number correct. The same thing meant any signed-in patient could read the
-- whole view: every booking's patient_id, doctor, date and session.
--
-- Rank over everyone, then hand back only the rows the caller is entitled to.
-- The ranking still counts the bookings it no longer shows.
-- -----------------------------------------------------------------------------
create or replace view public.booking_queue as
  with ranked as (
    select
      b.id as booking_id,
      b.doctor_id,
      b.patient_id,
      b.booked_date,
      b.session,
      b.status,
      row_number() over (
        partition by b.doctor_id, b.booked_date, b.session
        order by b.created_at, b.id
      )::integer as queue_number
    from public.bookings b
    where b.status <> 'cancelled'
  )
  select
    r.booking_id,
    r.doctor_id,
    r.patient_id,
    r.booked_date,
    r.session,
    r.status,
    r.queue_number
  from ranked r
  where r.patient_id = auth.uid()
     or r.doctor_id  = public.current_doctor_id()
     or public.is_admin();

grant select on public.booking_queue to authenticated, service_role;

-- anon has no bookings and no doctor, so every row was already filtered out for
-- it. Dropping the grant says so rather than leaving it to the filter.
revoke select on public.booking_queue from anon;

-- ############## 2 of 3 — REFERENCE DATA ##############
-- =============================================================================
-- Shefaa — reference data seed.
--
-- Rebuilds the master data that was lost: specialties, the governorate → city →
-- clinic tree, doctors, and bookable slots for the next 14 days.
--
-- Ported from Shefaa_Admin_Panel/src/infrastructure/seed/seed-data.ts, which is
-- the design's own data and the only surviving copy of this content.
--
-- Run AFTER migrations/0000_base_schema.sql. Safe to re-run: every insert is
-- `on conflict do nothing`, and the identity sequences are re-synced at the end.
--
-- NOT seeded on purpose:
--   * patients  — a profile row must match a real auth.users id. Restore those
--                 from auth.users instead (see the query at the bottom).
--   * bookings / payments — transactional history. Seeding fake rows here would
--                 put invented revenue on the admin dashboard.
-- =============================================================================

begin;

-- ---------- Governorates -----------------------------------------------------
insert into public."Governorates" (id, name) values
  (1, 'القاهرة'),
  (2, 'الجيزة'),
  (3, 'الإسكندرية'),
  (4, 'الدقهلية')
on conflict (id) do nothing;

-- ---------- Cities -----------------------------------------------------------
insert into public."Cities" (id, governorate_id, name) values
  (1, 1, 'مدينة نصر'),
  (2, 1, 'المعادي'),
  (3, 1, 'مصر الجديدة'),
  (4, 2, 'الدقي'),
  (5, 2, '٦ أكتوبر'),
  (6, 3, 'سموحة'),
  (7, 3, 'سيدي جابر'),
  (8, 4, 'المنصورة')
on conflict (id) do nothing;

-- ---------- Clinics ----------------------------------------------------------
insert into public."Clinics" (id, city_id, name) values
  (1,  1, 'مركز شفاء للقلب'),
  (2,  1, 'برج نصر الطبي'),
  (3,  2, 'عيادة المعادي للأسرة'),
  (4,  3, 'عيادة الكوربة التخصصية'),
  (5,  4, 'استوديو الدقي للأسنان'),
  (6,  5, 'مستشفى أكتوبر كير'),
  (7,  5, 'عيادات الشيخ زايد'),
  (8,  6, 'مركز سموحة للعيون'),
  (9,  7, 'عيادة الكورنيش للجلدية'),
  (10, 8, 'عيادة المنصورة للأطفال')
on conflict (id) do nothing;

-- ---------- Specialties ------------------------------------------------------
-- NOTE: the app renders `specialties.name` directly and its locale is fixed to
-- Arabic, so `name` holds the Arabic label. Migration 001 later added `name_ar`
-- for the admin panel; both are filled with the same value here. If you ever
-- switch `name` to English, update SpecialtyModel/the grid at the same time.
insert into public.specialties (id, name, name_ar, icon, color, base_fee, description) values
  (1,  'أمراض القلب',          'أمراض القلب',          'heart',      '#D6533F', 700, 'تشخيص وعلاج أمراض القلب والأوعية الدموية.'),
  (2,  'الجلدية',              'الجلدية',              'sparkle',    '#C98A1E', 500, 'العناية بأمراض الجلد والشعر والأظافر.'),
  (3,  'طب الأطفال',           'طب الأطفال',           'baby',       '#67B2D8', 450, 'الرعاية الطبية للرضع والأطفال والمراهقين.'),
  (4,  'العظام',               'العظام',               'bone',       '#5A8FB0', 550, 'رعاية العظام والمفاصل والأربطة والجهاز الحركي.'),
  (5,  'الأسنان',              'الأسنان',              'tooth',      '#7B6FCB', 500, 'صحة الفم وعلاج الأسنان وتجميلها.'),
  (6,  'المخ والأعصاب',        'المخ والأعصاب',        'brain',      '#9B7BC9', 650, 'اضطرابات المخ والعمود الفقري والجهاز العصبي.'),
  (7,  'النساء والتوليد',      'النساء والتوليد',      'heart',      '#D67BA0', 600, 'صحة المرأة الإنجابية ورعاية الحمل.'),
  (8,  'العيون',               'العيون',               'eye',        '#4A93BC', 500, 'فحص العيون والنظر والجراحة.'),
  (9,  'الأنف والأذن والحنجرة','الأنف والأذن والحنجرة','ear',        '#2E9E73', 450, 'تشخيص وعلاج الأنف والأذن والحنجرة.'),
  (10, 'الطب النفسي',          'الطب النفسي',          'brain',      '#6B7785', 600, 'تقييم الصحة النفسية والعلاج النفسي.')
on conflict (id) do nothing;

-- ---------- Doctors ----------------------------------------------------------
insert into public."Doctors"
  (id, name, specialization, specialty_id, clinic_id, consultation_fee, location, waiting_time, rating, status) values
  (1,  'د. أحمد السيد',   'أمراض القلب',           1,  1,  700, 'مركز شفاء للقلب - مدينة نصر',        20, 4.8, 'active'),
  (2,  'د. منى خليل',     'الجلدية',               2,  9,  600, 'عيادة الكورنيش للجلدية - سيدي جابر', 15, 4.6, 'active'),
  (3,  'د. طارق منصور',   'طب الأطفال',            3,  10, 450, 'عيادة المنصورة للأطفال - المنصورة',  25, 4.7, 'active'),
  (4,  'د. هناء فوزي',    'العظام',                4,  6,  550, 'مستشفى أكتوبر كير - ٦ أكتوبر',       30, 4.5, 'active'),
  (5,  'د. عمر سليم',     'الأسنان',               5,  5,  500, 'استوديو الدقي للأسنان - الدقي',      20, 4.9, 'active'),
  (6,  'د. نور عادل',     'المخ والأعصاب',         6,  4,  650, 'عيادة الكوربة التخصصية - مصر الجديدة',35, 4.4, 'inactive'),
  (7,  'د. ياسمين سعد',   'النساء والتوليد',       7,  3,  600, 'عيادة المعادي للأسرة - المعادي',     25, 4.8, 'active'),
  (8,  'د. خالد رشاد',    'العيون',                8,  8,  500, 'مركز سموحة للعيون - سموحة',          15, 4.6, 'active'),
  (9,  'د. سلمى جمال',    'الأنف والأذن والحنجرة', 9,  4,  450, 'عيادة الكوربة التخصصية - مصر الجديدة',20, 4.5, 'active'),
  (10, 'د. حسام نبيل',    'الطب النفسي',           10, 1,  800, 'مركز شفاء للقلب - مدينة نصر',        45, 4.9, 'active'),
  (11, 'د. دينا عزيز',    'الجلدية',               2,  9,  600, 'عيادة الكورنيش للجلدية - سيدي جابر', 20, 4.3, 'inactive'),
  (12, 'د. شريف لطفي',    'أمراض القلب',           1,  2,  750, 'برج نصر الطبي - مدينة نصر',          30, 4.7, 'active'),
  (13, 'د. رنا وائل',     'النساء والتوليد',       7,  3,  600, 'عيادة المعادي للأسرة - المعادي',     25, 4.8, 'active'),
  (14, 'د. كريم فؤاد',    'العظام',                4,  6,  520, 'مستشفى أكتوبر كير - ٦ أكتوبر',       30, 4.5, 'active')
on conflict (id) do nothing;

-- ---------- Bookable slots ---------------------------------------------------
-- 30-minute slots for the next 14 days, for every active doctor:
--   morning  09:00 → 13:00
--   evening  17:00 → 21:00
-- Fridays are skipped. This is what makes the booking flow testable end to end.
insert into public.doctor_availability (doctor_id, date, start_time, end_time, session, is_active)
select
  d.id,
  day::date,
  slot,
  slot + interval '30 minutes',
  case when slot < time '13:00' then 'morning' else 'evening' end,
  true
from public."Doctors" d
cross join generate_series(current_date, current_date + 13, interval '1 day') as day
cross join (
  select (time '09:00' + (n * interval '30 minutes')) as slot
  from generate_series(0, 7) as n            -- 09:00 .. 12:30
  union all
  select (time '17:00' + (n * interval '30 minutes'))
  from generate_series(0, 7) as n            -- 17:00 .. 20:30
) as slots
where d.status = 'active'
  and extract(dow from day) <> 5             -- 5 = Friday
on conflict (doctor_id, date, start_time) do nothing;

-- ---------- Weekly schedules -------------------------------------------------
-- The pattern each doctor works, from which availability is computed for any
-- date (see doctor_sessions_on). Capacities differ by what the specialty
-- actually does in a session: a dentist's list carries scalings and fillings,
-- a paediatrician's does not.
--
-- weekday: 0 = Sunday .. 6 = Saturday. Fridays are left out.
insert into public.doctor_schedule (doctor_id, weekday, session, start_time, end_time, capacity)
select d.doctor_id, w.weekday, d.session, d.start_time, d.end_time, d.capacity
from (values
  --  id, session,   from,    to,      cap, days
  (1,  'evening', '17:00'::time, '21:00'::time, 12, array[0,2,4]),  -- قلب
  (2,  'evening', '16:00'::time, '20:00'::time, 20, array[1,3]),    -- جلدية
  (3,  'morning', '09:00'::time, '13:00'::time, 25, array[0,1,2,3]),-- أطفال
  (4,  'evening', '17:00'::time, '21:00'::time, 16, array[2,4,6]),  -- عظام
  (5,  'evening', '17:00'::time, '21:00'::time,  8, array[0,2,4]),  -- أسنان
  (6,  'evening', '18:00'::time, '21:00'::time, 12, array[1,3]),    -- مخ وأعصاب
  (7,  'morning', '10:00'::time, '14:00'::time, 14, array[0,2,4]),  -- نساء
  (8,  'evening', '16:00'::time, '20:00'::time, 20, array[1,3,6]),  -- عيون
  (9,  'evening', '17:00'::time, '21:00'::time, 20, array[0,2,4]),  -- أنف وأذن
  (10, 'evening', '18:00'::time, '21:00'::time,  6, array[1,3]),    -- نفسي
  (11, 'morning', '09:00'::time, '13:00'::time, 20, array[2,4]),    -- جلدية
  (12, 'evening', '17:00'::time, '21:00'::time, 12, array[1,3,6]),  -- قلب
  (13, 'evening', '16:00'::time, '20:00'::time, 14, array[0,2]),    -- نساء
  (14, 'morning', '09:00'::time, '13:00'::time, 16, array[1,3,6])   -- عظام
) as d(doctor_id, session, start_time, end_time, capacity, days)
cross join lateral unnest(d.days) as w(weekday)
where exists (select 1 from public."Doctors" doc where doc.id = d.doctor_id)
on conflict (doctor_id, weekday, session) do nothing;

-- A second, morning list for the two busiest general specialties.
insert into public.doctor_schedule (doctor_id, weekday, session, start_time, end_time, capacity)
select d.doctor_id, w.weekday, 'morning', '09:00'::time, '12:00'::time, d.capacity
from (values (3, 20, array[4]), (9, 15, array[1,3])) as d(doctor_id, capacity, days)
cross join lateral unnest(d.days) as w(weekday)
where exists (select 1 from public."Doctors" doc where doc.id = d.doctor_id)
on conflict (doctor_id, weekday, session) do nothing;

-- ---------- Re-sync the identity sequences -----------------------------------
-- Explicit ids above bypass the sequences; without this the next INSERT that
-- relies on the default would collide with an id we just used.
select setval(pg_get_serial_sequence('public."Governorates"', 'id'),
              coalesce((select max(id) from public."Governorates"), 1), true);
select setval(pg_get_serial_sequence('public."Cities"', 'id'),
              coalesce((select max(id) from public."Cities"), 1), true);
select setval(pg_get_serial_sequence('public."Clinics"', 'id'),
              coalesce((select max(id) from public."Clinics"), 1), true);
select setval(pg_get_serial_sequence('public.specialties', 'id'),
              coalesce((select max(id) from public.specialties), 1), true);
select setval(pg_get_serial_sequence('public."Doctors"', 'id'),
              coalesce((select max(id) from public."Doctors"), 1), true);

commit;

-- =============================================================================
-- AFTERWARDS — restore the patient profiles from the surviving auth accounts.
--
-- auth.users lives in the `auth` schema, so a DELETE against the `public`
-- tables does not touch it. Check first:
--
--     select count(*) from auth.users;
--
-- If that returns your users, rebuild their profile rows:
--
--     insert into public.profiles (id, name)
--     select id, coalesce(raw_user_meta_data ->> 'name', split_part(email, '@', 1))
--     from auth.users
--     on conflict (id) do nothing;
--
-- Names/phones the users typed in are gone, but the accounts keep working and
-- the app stops erroring on a missing profile row.
-- =============================================================================

-- ############## 3 of 3 — SECURITY POLICIES ##############
-- =============================================================================
-- SECURITY FIX — replaces the wide-open policies created by 001_admin_integration.sql
--
-- 001 created, on profiles / "Doctors" / specialties / "Governorates" / "Cities"
-- / "Clinics":
--
--     create policy admin_manage on <table>
--       for all to authenticated using (true) with check (true);
--
-- `to authenticated` means EVERY signed-in user, and the patient app signs
-- every patient in. So any patient could read every other patient's profile
-- (name, phone, gender, birth date) and insert, update or delete any doctor,
-- specialty or clinic. This migration drops those policies and replaces them
-- with least-privilege ones.
--
-- Run this AFTER 001. It is idempotent.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Who is an admin?  Membership in public.admins — nothing else.
-- -----------------------------------------------------------------------------
create table if not exists public.admins (
  id         uuid primary key references auth.users (id) on delete cascade,
  name       text,
  created_at timestamptz not null default now()
);

alter table public.admins enable row level security;

drop policy if exists admins_self_read on public.admins;
create policy admins_self_read on public.admins
  for select to authenticated using (id = auth.uid());

-- SECURITY DEFINER so the lookup itself is not filtered by admins' own RLS.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where id = auth.uid());
$$;

revoke execute on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- -----------------------------------------------------------------------------
-- 2. Drop the permissive policies from 001.
-- -----------------------------------------------------------------------------
do $$
declare tbl text;
begin
  foreach tbl in array array[
    'specialties', '"Doctors"', '"Governorates"', '"Cities"', '"Clinics"', 'profiles'
  ]
  loop
    execute format('drop policy if exists admin_manage on public.%s;', tbl);
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- 3. Reference data — every signed-in user may READ; only admins may WRITE.
--    (specialties, doctors, the location tree, and the bookable slots)
-- -----------------------------------------------------------------------------
do $$
declare tbl text;
begin
  foreach tbl in array array[
    'specialties', '"Doctors"', '"Governorates"', '"Cities"', '"Clinics"',
    'doctor_availability'
  ]
  loop
    execute format('alter table public.%s enable row level security;', tbl);

    execute format('drop policy if exists ref_read_all on public.%s;', tbl);
    execute format(
      'create policy ref_read_all on public.%s
         for select to authenticated using (true);', tbl);

    execute format('drop policy if exists ref_admin_write on public.%s;', tbl);
    execute format(
      'create policy ref_admin_write on public.%s
         for all to authenticated
         using (public.is_admin()) with check (public.is_admin());', tbl);
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- 4. profiles — a patient sees and edits ONLY their own row. Admins see all.
-- -----------------------------------------------------------------------------
alter table public.profiles enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles
  for insert to authenticated
  with check (id = auth.uid());

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
  for update to authenticated
  using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());

-- Deleting a patient is an admin action only.
drop policy if exists profiles_delete_admin on public.profiles;
create policy profiles_delete_admin on public.profiles
  for delete to authenticated using (public.is_admin());

-- -----------------------------------------------------------------------------
-- 5. bookings — a patient sees and creates only their own.
--    Update is limited to their own row (so "cancel my booking" works);
--    deletes are admin-only so history is never silently destroyed.
-- -----------------------------------------------------------------------------
alter table public.bookings enable row level security;

drop policy if exists bookings_select_own on public.bookings;
create policy bookings_select_own on public.bookings
  for select to authenticated
  using (patient_id = auth.uid() or public.is_admin());

drop policy if exists bookings_insert_own on public.bookings;
create policy bookings_insert_own on public.bookings
  for insert to authenticated
  with check (patient_id = auth.uid());

drop policy if exists bookings_update_own on public.bookings;
create policy bookings_update_own on public.bookings
  for update to authenticated
  using (patient_id = auth.uid() or public.is_admin())
  with check (patient_id = auth.uid() or public.is_admin());

drop policy if exists bookings_delete_admin on public.bookings;
create policy bookings_delete_admin on public.bookings
  for delete to authenticated using (public.is_admin());

-- -----------------------------------------------------------------------------
-- 6. payments — a patient sees only their own.
--
--    NOTE: the insert policy below is a STOPGAP. The app still creates the
--    payment row itself with status 'paid' and a client-supplied amount, so a
--    patient can still book for any price they like. The real fix is to move
--    booking + payment creation into an Edge Function (service role) and then
--    drop this insert policy entirely. Tracked as the next task.
-- -----------------------------------------------------------------------------
alter table public.payments enable row level security;

drop policy if exists payments_select_own on public.payments;
create policy payments_select_own on public.payments
  for select to authenticated
  using (patient_id = auth.uid() or public.is_admin());

drop policy if exists payments_insert_own on public.payments;
create policy payments_insert_own on public.payments
  for insert to authenticated
  with check (patient_id = auth.uid());

drop policy if exists payments_write_admin on public.payments;
create policy payments_write_admin on public.payments
  for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists payments_delete_admin on public.payments;
create policy payments_delete_admin on public.payments
  for delete to authenticated using (public.is_admin());

-- -----------------------------------------------------------------------------
-- 7. Promote your first admin (run once, by hand, with your own user id):
--
--     insert into public.admins (id, name)
--     select id, 'Owner' from auth.users where email = 'you@example.com'
--     on conflict (id) do nothing;
--
-- Until you do this, the admin panel will read empty lists — that is the
-- policies working correctly, not a bug.
-- -----------------------------------------------------------------------------

-- =============================================================================
-- AFTER RUNNING THE ABOVE — two steps that need your own values.
--
--  1. Create your account:
--     Dashboard -> Authentication -> Users -> Add user
--     Tick "Auto Confirm User". A profiles row is created by trigger.
--
--  2. Make yourself an admin (without this the admin panel reads empty,
--     which is the policies working, not a bug):
--
--       insert into public.admins (id, name)
--       select id, 'Owner' from auth.users where email = 'YOUR_EMAIL_HERE'
--       on conflict (id) do nothing;
--
--  Then check:  10 specialties · 14 doctors · ~2304 slots · 1 admin
-- =============================================================================
