-- =============================================================================
-- Shefaa — full restore, in one paste.
--
-- Supabase Dashboard -> SQL Editor -> New query -> paste all of this -> Run.
--
-- GENERATED FILE — do not edit. Run ./scripts/build-restore.sh instead.
-- Sources:
--   supabase/migrations/0000_base_schema.sql
--   supabase/seed.sql
--   ../Shefaa_Admin_Panel/supabase/migrations/002_fix_rls_policies.sql
--
-- Safe to re-run: every statement is if-not-exists / on-conflict-do-nothing.
-- Two manual steps follow at the bottom.
-- =============================================================================

-- ############## 1 of 3 — SCHEMA ##############
-- =============================================================================
-- Shefaa — Base schema for the patient app.
--
-- IMPORTANT — HOW THIS FILE CAME TO BE
-- This schema was RECONSTRUCTED by reading the Dart data models in `lib/`
-- (the column names the app actually reads and writes) plus the additive
-- migrations in the admin-panel and doctor-dashboard repos. It was NOT dumped
-- from the live database, because the live schema had never been committed
-- anywhere.
--
-- Treat it as a starting point, not as the authority. As soon as you have a
-- working database again, replace this file with a real dump:
--
--     supabase db dump --db-url "$DB_URL" -f supabase/migrations/0000_base_schema.sql
--
-- Every statement is idempotent (`if not exists`), so running it against a
-- database that still has its tables will not destroy anything.
-- =============================================================================

create extension if not exists "pgcrypto";

-- -----------------------------------------------------------------------------
-- Location hierarchy: Governorate -> City -> Clinic
-- Quoted capitalised names match what the app and admin panel already query.
-- -----------------------------------------------------------------------------
create table if not exists public."Governorates" (
  id         bigint generated by default as identity primary key,
  name       text not null,
  created_at timestamptz not null default now()
);

create table if not exists public."Cities" (
  id             bigint generated by default as identity primary key,
  governorate_id bigint references public."Governorates" (id) on delete cascade,
  name           text not null,
  created_at     timestamptz not null default now()
);

create table if not exists public."Clinics" (
  id         bigint generated by default as identity primary key,
  city_id    bigint references public."Cities" (id) on delete cascade,
  name       text not null,
  address    text,
  created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Specialties — read by the app's home screen (HomeRemoteDatasource).
-- -----------------------------------------------------------------------------
create table if not exists public.specialties (
  id          bigint generated by default as identity primary key,
  name        text not null,
  icon        text,
  name_ar     text,
  description text,
  color       text,
  base_fee    numeric(10,2) default 0,
  created_at  timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Doctors — columns taken from DoctorModel.fromMap / toMap.
-- -----------------------------------------------------------------------------
create table if not exists public."Doctors" (
  id               bigint generated by default as identity primary key,
  name             text not null,
  title            text,
  specialization   text,
  specialty_id     bigint references public.specialties (id) on delete set null,
  clinic_id        bigint references public."Clinics" (id) on delete set null,
  image            text,
  location         text,
  rating           numeric(3,2) default 0 check (rating >= 0 and rating <= 5),
  consultation_fee numeric(10,2) not null default 0 check (consultation_fee >= 0),
  waiting_time     integer check (waiting_time >= 0),
  status           text not null default 'active',
  created_at       timestamptz not null default now()
);

create index if not exists doctors_specialty_idx on public."Doctors" (specialty_id);
create index if not exists doctors_clinic_idx    on public."Doctors" (clinic_id);

-- -----------------------------------------------------------------------------
-- Profiles — the patient record, keyed 1:1 to auth.users.
-- Written by AuthRemoteDataSource.register / read by ProfileRemoteDataSource.
-- -----------------------------------------------------------------------------
create table if not exists public.profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  name       text,
  phone      text,
  gender     text check (gender is null or gender in ('male', 'female')),
  birth_date date,
  status     text not null default 'active',
  created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Doctor availability — the bookable slots.
-- -----------------------------------------------------------------------------
create table if not exists public.doctor_availability (
  id         bigint generated by default as identity primary key,
  doctor_id  bigint not null references public."Doctors" (id) on delete cascade,
  date       date not null,
  start_time time not null,
  end_time   time not null,
  session    text not null check (session in ('morning', 'evening')),
  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  constraint doctor_availability_time_order check (end_time > start_time),
  -- A doctor cannot have the same slot listed twice.
  constraint doctor_availability_unique_slot unique (doctor_id, date, start_time)
);

create index if not exists doctor_availability_lookup_idx
  on public.doctor_availability (doctor_id, date, is_active);

-- -----------------------------------------------------------------------------
-- Payments — created alongside a booking.
-- -----------------------------------------------------------------------------
create table if not exists public.payments (
  id             bigint generated by default as identity primary key,
  patient_id     uuid references public.profiles (id) on delete set null,
  amount         numeric(10,2) not null check (amount >= 0),
  payment_method text not null check (payment_method in ('cash', 'instapay', 'card')),
  status         text not null default 'pending'
                   check (status in ('pending', 'paid', 'refunded', 'failed')),
  created_at     timestamptz not null default now()
);

create index if not exists payments_patient_idx on public.payments (patient_id);

-- -----------------------------------------------------------------------------
-- Bookings — the appointment itself.
-- -----------------------------------------------------------------------------
create table if not exists public.bookings (
  id          bigint generated by default as identity primary key,
  patient_id  uuid not null references public.profiles (id) on delete cascade,
  doctor_id   bigint not null references public."Doctors" (id) on delete cascade,
  payment_id  bigint references public.payments (id) on delete set null,
  booked_date date not null,
  start_time  time not null,
  end_time    time not null,
  -- 'no_show' matters for revenue: a patient who books and never arrives must be
  -- distinguishable from one who attended, or commission cannot be computed later.
  -- The doctor dashboard already sends this value (appointment.labels.ts).
  status      text not null default 'pending'
                check (status in ('pending', 'confirmed', 'completed', 'cancelled', 'no_show')),
  created_at  timestamptz not null default now()
);

create index if not exists bookings_patient_idx on public.bookings (patient_id);
create index if not exists bookings_doctor_idx  on public.bookings (doctor_id, booked_date);
create index if not exists bookings_status_idx  on public.bookings (status);

-- A doctor cannot be double-booked for the same slot. Cancelled bookings are
-- excluded so a cancelled slot can be rebooked.
create unique index if not exists bookings_no_double_booking
  on public.bookings (doctor_id, booked_date, start_time)
  where status <> 'cancelled';

-- -----------------------------------------------------------------------------
-- Admins — membership in this table is what grants admin-panel access.
-- Referenced by the is_admin() helper used in the RLS policies.
-- -----------------------------------------------------------------------------
create table if not exists public.admins (
  id         uuid primary key references auth.users (id) on delete cascade,
  name       text,
  created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Keep a profile row in step with every auth user, so a signup can never end up
-- with an auth account but no profile (the app currently inserts the profile
-- client-side, which silently fails when email confirmation is on).
-- -----------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ############## 2 of 3 — REFERENCE DATA ##############
-- =============================================================================
-- Shefaa — reference data seed.
--
-- Rebuilds the master data that was lost: specialties, the governorate → city →
-- clinic tree, doctors, and bookable slots for the next 14 days.
--
-- Ported from Shefaa_Admin_Panel/src/infrastructure/seed/seed-data.ts, which is
-- the design's own data and the only surviving copy of this content.
--
-- Run AFTER migrations/0000_base_schema.sql. Safe to re-run: every insert is
-- `on conflict do nothing`, and the identity sequences are re-synced at the end.
--
-- NOT seeded on purpose:
--   * patients  — a profile row must match a real auth.users id. Restore those
--                 from auth.users instead (see the query at the bottom).
--   * bookings / payments — transactional history. Seeding fake rows here would
--                 put invented revenue on the admin dashboard.
-- =============================================================================

begin;

-- ---------- Governorates -----------------------------------------------------
insert into public."Governorates" (id, name) values
  (1, 'القاهرة'),
  (2, 'الجيزة'),
  (3, 'الإسكندرية'),
  (4, 'الدقهلية')
on conflict (id) do nothing;

-- ---------- Cities -----------------------------------------------------------
insert into public."Cities" (id, governorate_id, name) values
  (1, 1, 'مدينة نصر'),
  (2, 1, 'المعادي'),
  (3, 1, 'مصر الجديدة'),
  (4, 2, 'الدقي'),
  (5, 2, '٦ أكتوبر'),
  (6, 3, 'سموحة'),
  (7, 3, 'سيدي جابر'),
  (8, 4, 'المنصورة')
on conflict (id) do nothing;

-- ---------- Clinics ----------------------------------------------------------
insert into public."Clinics" (id, city_id, name) values
  (1,  1, 'مركز شفاء للقلب'),
  (2,  1, 'برج نصر الطبي'),
  (3,  2, 'عيادة المعادي للأسرة'),
  (4,  3, 'عيادة الكوربة التخصصية'),
  (5,  4, 'استوديو الدقي للأسنان'),
  (6,  5, 'مستشفى أكتوبر كير'),
  (7,  5, 'عيادات الشيخ زايد'),
  (8,  6, 'مركز سموحة للعيون'),
  (9,  7, 'عيادة الكورنيش للجلدية'),
  (10, 8, 'عيادة المنصورة للأطفال')
on conflict (id) do nothing;

-- ---------- Specialties ------------------------------------------------------
-- NOTE: the app renders `specialties.name` directly and its locale is fixed to
-- Arabic, so `name` holds the Arabic label. Migration 001 later added `name_ar`
-- for the admin panel; both are filled with the same value here. If you ever
-- switch `name` to English, update SpecialtyModel/the grid at the same time.
insert into public.specialties (id, name, name_ar, icon, color, base_fee, description) values
  (1,  'أمراض القلب',          'أمراض القلب',          'heart',      '#D6533F', 700, 'تشخيص وعلاج أمراض القلب والأوعية الدموية.'),
  (2,  'الجلدية',              'الجلدية',              'sparkle',    '#C98A1E', 500, 'العناية بأمراض الجلد والشعر والأظافر.'),
  (3,  'طب الأطفال',           'طب الأطفال',           'baby',       '#67B2D8', 450, 'الرعاية الطبية للرضع والأطفال والمراهقين.'),
  (4,  'العظام',               'العظام',               'bone',       '#5A8FB0', 550, 'رعاية العظام والمفاصل والأربطة والجهاز الحركي.'),
  (5,  'الأسنان',              'الأسنان',              'tooth',      '#7B6FCB', 500, 'صحة الفم وعلاج الأسنان وتجميلها.'),
  (6,  'المخ والأعصاب',        'المخ والأعصاب',        'brain',      '#9B7BC9', 650, 'اضطرابات المخ والعمود الفقري والجهاز العصبي.'),
  (7,  'النساء والتوليد',      'النساء والتوليد',      'heart',      '#D67BA0', 600, 'صحة المرأة الإنجابية ورعاية الحمل.'),
  (8,  'العيون',               'العيون',               'eye',        '#4A93BC', 500, 'فحص العيون والنظر والجراحة.'),
  (9,  'الأنف والأذن والحنجرة','الأنف والأذن والحنجرة','ear',        '#2E9E73', 450, 'تشخيص وعلاج الأنف والأذن والحنجرة.'),
  (10, 'الطب النفسي',          'الطب النفسي',          'brain',      '#6B7785', 600, 'تقييم الصحة النفسية والعلاج النفسي.')
on conflict (id) do nothing;

-- ---------- Doctors ----------------------------------------------------------
insert into public."Doctors"
  (id, name, specialization, specialty_id, clinic_id, consultation_fee, location, waiting_time, rating, status) values
  (1,  'د. أحمد السيد',   'أمراض القلب',           1,  1,  700, 'مركز شفاء للقلب - مدينة نصر',        20, 4.8, 'active'),
  (2,  'د. منى خليل',     'الجلدية',               2,  9,  600, 'عيادة الكورنيش للجلدية - سيدي جابر', 15, 4.6, 'active'),
  (3,  'د. طارق منصور',   'طب الأطفال',            3,  10, 450, 'عيادة المنصورة للأطفال - المنصورة',  25, 4.7, 'active'),
  (4,  'د. هناء فوزي',    'العظام',                4,  6,  550, 'مستشفى أكتوبر كير - ٦ أكتوبر',       30, 4.5, 'active'),
  (5,  'د. عمر سليم',     'الأسنان',               5,  5,  500, 'استوديو الدقي للأسنان - الدقي',      20, 4.9, 'active'),
  (6,  'د. نور عادل',     'المخ والأعصاب',         6,  4,  650, 'عيادة الكوربة التخصصية - مصر الجديدة',35, 4.4, 'inactive'),
  (7,  'د. ياسمين سعد',   'النساء والتوليد',       7,  3,  600, 'عيادة المعادي للأسرة - المعادي',     25, 4.8, 'active'),
  (8,  'د. خالد رشاد',    'العيون',                8,  8,  500, 'مركز سموحة للعيون - سموحة',          15, 4.6, 'active'),
  (9,  'د. سلمى جمال',    'الأنف والأذن والحنجرة', 9,  4,  450, 'عيادة الكوربة التخصصية - مصر الجديدة',20, 4.5, 'active'),
  (10, 'د. حسام نبيل',    'الطب النفسي',           10, 1,  800, 'مركز شفاء للقلب - مدينة نصر',        45, 4.9, 'active'),
  (11, 'د. دينا عزيز',    'الجلدية',               2,  9,  600, 'عيادة الكورنيش للجلدية - سيدي جابر', 20, 4.3, 'inactive'),
  (12, 'د. شريف لطفي',    'أمراض القلب',           1,  2,  750, 'برج نصر الطبي - مدينة نصر',          30, 4.7, 'active'),
  (13, 'د. رنا وائل',     'النساء والتوليد',       7,  3,  600, 'عيادة المعادي للأسرة - المعادي',     25, 4.8, 'active'),
  (14, 'د. كريم فؤاد',    'العظام',                4,  6,  520, 'مستشفى أكتوبر كير - ٦ أكتوبر',       30, 4.5, 'active')
on conflict (id) do nothing;

-- ---------- Bookable slots ---------------------------------------------------
-- 30-minute slots for the next 14 days, for every active doctor:
--   morning  09:00 → 13:00
--   evening  17:00 → 21:00
-- Fridays are skipped. This is what makes the booking flow testable end to end.
insert into public.doctor_availability (doctor_id, date, start_time, end_time, session, is_active)
select
  d.id,
  day::date,
  slot,
  slot + interval '30 minutes',
  case when slot < time '13:00' then 'morning' else 'evening' end,
  true
from public."Doctors" d
cross join generate_series(current_date, current_date + 13, interval '1 day') as day
cross join (
  select (time '09:00' + (n * interval '30 minutes')) as slot
  from generate_series(0, 7) as n            -- 09:00 .. 12:30
  union all
  select (time '17:00' + (n * interval '30 minutes'))
  from generate_series(0, 7) as n            -- 17:00 .. 20:30
) as slots
where d.status = 'active'
  and extract(dow from day) <> 5             -- 5 = Friday
on conflict (doctor_id, date, start_time) do nothing;

-- ---------- Re-sync the identity sequences -----------------------------------
-- Explicit ids above bypass the sequences; without this the next INSERT that
-- relies on the default would collide with an id we just used.
select setval(pg_get_serial_sequence('public."Governorates"', 'id'),
              coalesce((select max(id) from public."Governorates"), 1), true);
select setval(pg_get_serial_sequence('public."Cities"', 'id'),
              coalesce((select max(id) from public."Cities"), 1), true);
select setval(pg_get_serial_sequence('public."Clinics"', 'id'),
              coalesce((select max(id) from public."Clinics"), 1), true);
select setval(pg_get_serial_sequence('public.specialties', 'id'),
              coalesce((select max(id) from public.specialties), 1), true);
select setval(pg_get_serial_sequence('public."Doctors"', 'id'),
              coalesce((select max(id) from public."Doctors"), 1), true);

commit;

-- =============================================================================
-- AFTERWARDS — restore the patient profiles from the surviving auth accounts.
--
-- auth.users lives in the `auth` schema, so a DELETE against the `public`
-- tables does not touch it. Check first:
--
--     select count(*) from auth.users;
--
-- If that returns your users, rebuild their profile rows:
--
--     insert into public.profiles (id, name)
--     select id, coalesce(raw_user_meta_data ->> 'name', split_part(email, '@', 1))
--     from auth.users
--     on conflict (id) do nothing;
--
-- Names/phones the users typed in are gone, but the accounts keep working and
-- the app stops erroring on a missing profile row.
-- =============================================================================

-- ############## 3 of 3 — SECURITY POLICIES ##############
-- =============================================================================
-- SECURITY FIX — replaces the wide-open policies created by 001_admin_integration.sql
--
-- 001 created, on profiles / "Doctors" / specialties / "Governorates" / "Cities"
-- / "Clinics":
--
--     create policy admin_manage on <table>
--       for all to authenticated using (true) with check (true);
--
-- `to authenticated` means EVERY signed-in user, and the patient app signs
-- every patient in. So any patient could read every other patient's profile
-- (name, phone, gender, birth date) and insert, update or delete any doctor,
-- specialty or clinic. This migration drops those policies and replaces them
-- with least-privilege ones.
--
-- Run this AFTER 001. It is idempotent.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Who is an admin?  Membership in public.admins — nothing else.
-- -----------------------------------------------------------------------------
create table if not exists public.admins (
  id         uuid primary key references auth.users (id) on delete cascade,
  name       text,
  created_at timestamptz not null default now()
);

alter table public.admins enable row level security;

drop policy if exists admins_self_read on public.admins;
create policy admins_self_read on public.admins
  for select to authenticated using (id = auth.uid());

-- SECURITY DEFINER so the lookup itself is not filtered by admins' own RLS.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where id = auth.uid());
$$;

revoke execute on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- -----------------------------------------------------------------------------
-- 2. Drop the permissive policies from 001.
-- -----------------------------------------------------------------------------
do $$
declare tbl text;
begin
  foreach tbl in array array[
    'specialties', '"Doctors"', '"Governorates"', '"Cities"', '"Clinics"', 'profiles'
  ]
  loop
    execute format('drop policy if exists admin_manage on public.%s;', tbl);
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- 3. Reference data — every signed-in user may READ; only admins may WRITE.
--    (specialties, doctors, the location tree, and the bookable slots)
-- -----------------------------------------------------------------------------
do $$
declare tbl text;
begin
  foreach tbl in array array[
    'specialties', '"Doctors"', '"Governorates"', '"Cities"', '"Clinics"',
    'doctor_availability'
  ]
  loop
    execute format('alter table public.%s enable row level security;', tbl);

    execute format('drop policy if exists ref_read_all on public.%s;', tbl);
    execute format(
      'create policy ref_read_all on public.%s
         for select to authenticated using (true);', tbl);

    execute format('drop policy if exists ref_admin_write on public.%s;', tbl);
    execute format(
      'create policy ref_admin_write on public.%s
         for all to authenticated
         using (public.is_admin()) with check (public.is_admin());', tbl);
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- 4. profiles — a patient sees and edits ONLY their own row. Admins see all.
-- -----------------------------------------------------------------------------
alter table public.profiles enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles
  for insert to authenticated
  with check (id = auth.uid());

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
  for update to authenticated
  using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());

-- Deleting a patient is an admin action only.
drop policy if exists profiles_delete_admin on public.profiles;
create policy profiles_delete_admin on public.profiles
  for delete to authenticated using (public.is_admin());

-- -----------------------------------------------------------------------------
-- 5. bookings — a patient sees and creates only their own.
--    Update is limited to their own row (so "cancel my booking" works);
--    deletes are admin-only so history is never silently destroyed.
-- -----------------------------------------------------------------------------
alter table public.bookings enable row level security;

drop policy if exists bookings_select_own on public.bookings;
create policy bookings_select_own on public.bookings
  for select to authenticated
  using (patient_id = auth.uid() or public.is_admin());

drop policy if exists bookings_insert_own on public.bookings;
create policy bookings_insert_own on public.bookings
  for insert to authenticated
  with check (patient_id = auth.uid());

drop policy if exists bookings_update_own on public.bookings;
create policy bookings_update_own on public.bookings
  for update to authenticated
  using (patient_id = auth.uid() or public.is_admin())
  with check (patient_id = auth.uid() or public.is_admin());

drop policy if exists bookings_delete_admin on public.bookings;
create policy bookings_delete_admin on public.bookings
  for delete to authenticated using (public.is_admin());

-- -----------------------------------------------------------------------------
-- 6. payments — a patient sees only their own.
--
--    NOTE: the insert policy below is a STOPGAP. The app still creates the
--    payment row itself with status 'paid' and a client-supplied amount, so a
--    patient can still book for any price they like. The real fix is to move
--    booking + payment creation into an Edge Function (service role) and then
--    drop this insert policy entirely. Tracked as the next task.
-- -----------------------------------------------------------------------------
alter table public.payments enable row level security;

drop policy if exists payments_select_own on public.payments;
create policy payments_select_own on public.payments
  for select to authenticated
  using (patient_id = auth.uid() or public.is_admin());

drop policy if exists payments_insert_own on public.payments;
create policy payments_insert_own on public.payments
  for insert to authenticated
  with check (patient_id = auth.uid());

drop policy if exists payments_write_admin on public.payments;
create policy payments_write_admin on public.payments
  for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists payments_delete_admin on public.payments;
create policy payments_delete_admin on public.payments
  for delete to authenticated using (public.is_admin());

-- -----------------------------------------------------------------------------
-- 7. Promote your first admin (run once, by hand, with your own user id):
--
--     insert into public.admins (id, name)
--     select id, 'Owner' from auth.users where email = 'you@example.com'
--     on conflict (id) do nothing;
--
-- Until you do this, the admin panel will read empty lists — that is the
-- policies working correctly, not a bug.
-- -----------------------------------------------------------------------------

-- =============================================================================
-- AFTER RUNNING THE ABOVE — two steps that need your own values.
--
--  1. Create your account:
--     Dashboard -> Authentication -> Users -> Add user
--     Tick "Auto Confirm User". A profiles row is created by trigger.
--
--  2. Make yourself an admin (without this the admin panel reads empty,
--     which is the policies working, not a bug):
--
--       insert into public.admins (id, name)
--       select id, 'Owner' from auth.users where email = 'YOUR_EMAIL_HERE'
--       on conflict (id) do nothing;
--
--  Then check:  10 specialties · 14 doctors · ~2304 slots · 1 admin
-- =============================================================================
