// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4yq6TX0oRK1UkQ9EC0deiOuEKdmjGerI',
    appId: '1:1095458291175:web:97801cc6fb45d6f725d142',
    messagingSenderId: '1095458291175',
    projectId: 'shefaa-717db',
    authDomain: 'shefaa-717db.firebaseapp.com',
    storageBucket: 'shefaa-717db.firebasestorage.app',
    measurementId: 'G-D7G1ZHLNKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4XmvGoF68hART1cBe9PX841gluczHA_Q',
    appId: '1:1095458291175:android:3c903155648e59fc25d142',
    messagingSenderId: '1095458291175',
    projectId: 'shefaa-717db',
    storageBucket: 'shefaa-717db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-_1mCx9GaEiU7gbUUVQdof2qp1g-C0JA',
    appId: '1:1095458291175:ios:ea1ada7f1d3fd32025d142',
    messagingSenderId: '1095458291175',
    projectId: 'shefaa-717db',
    storageBucket: 'shefaa-717db.firebasestorage.app',
    iosBundleId: 'eg.shefaa.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-_1mCx9GaEiU7gbUUVQdof2qp1g-C0JA',
    appId: '1:1095458291175:ios:83532f6688290a1525d142',
    messagingSenderId: '1095458291175',
    projectId: 'shefaa-717db',
    storageBucket: 'shefaa-717db.firebasestorage.app',
    iosBundleId: 'com.example.shefaaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4yq6TX0oRK1UkQ9EC0deiOuEKdmjGerI',
    appId: '1:1095458291175:web:e72e702072f3a6f725d142',
    messagingSenderId: '1095458291175',
    projectId: 'shefaa-717db',
    authDomain: 'shefaa-717db.firebaseapp.com',
    storageBucket: 'shefaa-717db.firebasestorage.app',
    measurementId: 'G-3DR1HPCVN9',
  );
}
