-- =============================================================================
-- Shefaa — Base schema for the patient app.
--
-- IMPORTANT — HOW THIS FILE CAME TO BE
-- This schema was RECONSTRUCTED by reading the Dart data models in `lib/`
-- (the column names the app actually reads and writes) plus the additive
-- migrations in the admin-panel and doctor-dashboard repos. It was NOT dumped
-- from the live database, because the live schema had never been committed
-- anywhere.
--
-- Treat it as a starting point, not as the authority. As soon as you have a
-- working database again, replace this file with a real dump:
--
--     supabase db dump --db-url "$DB_URL" -f supabase/migrations/0000_base_schema.sql
--
-- Every statement is idempotent (`if not exists`), so running it against a
-- database that still has its tables will not destroy anything.
-- =============================================================================

create extension if not exists "pgcrypto";

-- -----------------------------------------------------------------------------
-- Location hierarchy: Governorate -> City -> Clinic
-- Quoted capitalised names match what the app and admin panel already query.
-- -----------------------------------------------------------------------------
create table if not exists public."Governorates" (
  id         bigint generated by default as identity primary key,
  name       text not null,
  created_at timestamptz not null default now()
);

create table if not exists public."Cities" (
  id             bigint generated by default as identity primary key,
  governorate_id bigint references public."Governorates" (id) on delete cascade,
  name           text not null,
  created_at     timestamptz not null default now()
);

create table if not exists public."Clinics" (
  id         bigint generated by default as identity primary key,
  city_id    bigint references public."Cities" (id) on delete cascade,
  name       text not null,
  address    text,
  created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Specialties — read by the app's home screen (HomeRemoteDatasource).
-- -----------------------------------------------------------------------------
create table if not exists public.specialties (
  id          bigint generated by default as identity primary key,
  name        text not null,
  icon        text,
  name_ar     text,
  description text,
  color       text,
  base_fee    numeric(10,2) default 0,
  created_at  timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Doctors — columns taken from DoctorModel.fromMap / toMap.
-- -----------------------------------------------------------------------------
create table if not exists public."Doctors" (
  id               bigint generated by default as identity primary key,
  name             text not null,
  title            text,
  specialization   text,
  specialty_id     bigint references public.specialties (id) on delete set null,
  clinic_id        bigint references public."Clinics" (id) on delete set null,
  image            text,
  location         text,
  rating           numeric(3,2) default 0 check (rating >= 0 and rating <= 5),
  consultation_fee numeric(10,2) not null default 0 check (consultation_fee >= 0),
  waiting_time     integer check (waiting_time >= 0),
  status           text not null default 'active',

  -- The other two apps depend on these: the admin panel writes email, and the
  -- doctor dashboard finds the signed-in doctor through user_id. Reconstructing
  -- this table from the Flutter models alone left them out.
  email            text,
  user_id          uuid references auth.users (id) on delete set null,
  phone            text,
  bio              text,
  license_number   text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create unique index if not exists doctors_user_id_key
  on public."Doctors" (user_id) where user_id is not null;
create unique index if not exists doctors_email_key
  on public."Doctors" (lower(email)) where email is not null;

create index if not exists doctors_specialty_idx on public."Doctors" (specialty_id);
create index if not exists doctors_clinic_idx    on public."Doctors" (clinic_id);

-- -----------------------------------------------------------------------------
-- Profiles — the patient record, keyed 1:1 to auth.users.
-- Written by AuthRemoteDataSource.register / read by ProfileRemoteDataSource.
-- -----------------------------------------------------------------------------
create table if not exists public.profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  name       text,
  phone      text,
  gender     text check (gender is null or gender in ('male', 'female')),
  birth_date date,
  status     text not null default 'active',
  created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Doctor availability — the bookable slots.
-- -----------------------------------------------------------------------------
create table if not exists public.doctor_availability (
  id         bigint generated by default as identity primary key,
  doctor_id  bigint not null references public."Doctors" (id) on delete cascade,
  date       date not null,
  start_time time not null,
  end_time   time not null,
  session    text not null check (session in ('morning', 'evening')),
  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  constraint doctor_availability_time_order check (end_time > start_time),
  -- A doctor cannot have the same slot listed twice.
  constraint doctor_availability_unique_slot unique (doctor_id, date, start_time)
);

create index if not exists doctor_availability_lookup_idx
  on public.doctor_availability (doctor_id, date, is_active);

-- -----------------------------------------------------------------------------
-- Payments — created alongside a booking.
-- -----------------------------------------------------------------------------
create table if not exists public.payments (
  id             bigint generated by default as identity primary key,
  patient_id     uuid references public.profiles (id) on delete set null,
  amount         numeric(10,2) not null check (amount >= 0),
  payment_method text not null check (payment_method in ('cash', 'instapay', 'card')),
  status         text not null default 'pending'
                   check (status in ('pending', 'paid', 'refunded', 'failed')),
  created_at     timestamptz not null default now()
);

create index if not exists payments_patient_idx on public.payments (patient_id);

-- -----------------------------------------------------------------------------
-- Bookings — the appointment itself.
-- -----------------------------------------------------------------------------
create table if not exists public.bookings (
  id          bigint generated by default as identity primary key,
  patient_id  uuid not null references public.profiles (id) on delete cascade,
  doctor_id   bigint not null references public."Doctors" (id) on delete cascade,
  payment_id  bigint references public.payments (id) on delete set null,
  booked_date date not null,
  start_time  time not null,
  end_time    time not null,
  -- 'no_show' matters for revenue: a patient who books and never arrives must be
  -- distinguishable from one who attended, or commission cannot be computed later.
  -- The doctor dashboard already sends this value (appointment.labels.ts).
  status      text not null default 'pending'
                check (status in ('pending', 'confirmed', 'completed', 'cancelled', 'no_show')),
  created_at  timestamptz not null default now()
);

create index if not exists bookings_patient_idx on public.bookings (patient_id);
create index if not exists bookings_doctor_idx  on public.bookings (doctor_id, booked_date);
create index if not exists bookings_status_idx  on public.bookings (status);

-- A doctor cannot be double-booked for the same slot. Cancelled bookings are
-- excluded so a cancelled slot can be rebooked.
create unique index if not exists bookings_no_double_booking
  on public.bookings (doctor_id, booked_date, start_time)
  where status <> 'cancelled';

-- -----------------------------------------------------------------------------
-- Admins — membership in this table is what grants admin-panel access.
-- Referenced by the is_admin() helper used in the RLS policies.
-- -----------------------------------------------------------------------------
create table if not exists public.admins (
  id         uuid primary key references auth.users (id) on delete cascade,
  name       text,
  created_at timestamptz not null default now()
);

-- Admin status comes from membership in public.admins and nothing else.
-- SECURITY DEFINER so the lookup is not itself filtered by admins' own RLS.
-- Defined here, with the table, because migrations that add policies depend on
-- it -- 0004 referenced it before the RLS migration had created it.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where id = auth.uid());
$$;

-- -----------------------------------------------------------------------------
-- Keep a profile row in step with every auth user, so a signup can never end up
-- with an auth account but no profile (the app currently inserts the profile
-- client-side, which silently fails when email confirmation is on).
-- -----------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- -----------------------------------------------------------------------------
-- Table privileges for the Supabase roles.
--
-- RLS decides which rows a role sees; GRANT decides whether it may read the
-- table at all. Without this every app query fails with 42501, whatever the
-- policies say. Not `grant all`: that includes TRUNCATE, which ignores RLS.
-- -----------------------------------------------------------------------------
grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant select on all tables in schema public to anon;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

alter default privileges in schema public
  grant select, insert, update, delete on tables to authenticated;
alter default privileges in schema public
  grant select on tables to anon;
alter default privileges in schema public
  grant all on tables to service_role;
alter default privileges in schema public
  grant usage, select on sequences to anon, authenticated, service_role;
