-- =============================================================================
-- Weekly schedules, replacing the per-date availability rows.
--
-- doctor_availability stored one row per concrete date and time, so somebody
-- had to keep inserting rows forever. The seed generated 14 days; on day 15
-- every doctor would have shown no availability and the app would have said
-- "no slots" as though that were normal.
--
-- A doctor's working week is a pattern, so it is stored as one. Availability
-- for any date is computed from that pattern, which means it never expires and
-- changing the pattern needs no regeneration.
--
-- doctor_availability is NOT dropped here: the app still reads it. It goes when
-- the screens move over.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- The weekly pattern. 2-6 rows per doctor instead of thousands.
-- -----------------------------------------------------------------------------
create table if not exists public.doctor_schedule (
  id         bigint generated by default as identity primary key,
  doctor_id  bigint not null references public."Doctors" (id) on delete cascade,
  weekday    smallint not null check (weekday between 0 and 6),  -- 0 = Sunday, matching extract(dow)
  session    text not null check (session in ('morning', 'evening')),
  start_time time not null,
  end_time   time not null,

  -- How many patients the doctor takes in this session. Entered directly
  -- rather than derived from an average visit length: a dentist whose list
  -- mixes a 10-minute check with a 45-minute scaling knows their own number,
  -- and any average we computed would be worse than their estimate.
  capacity   integer not null check (capacity > 0),

  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint doctor_schedule_time_order check (end_time > start_time),
  unique (doctor_id, weekday, session)
);

create index if not exists doctor_schedule_lookup_idx
  on public.doctor_schedule (doctor_id, weekday) where is_active;

-- -----------------------------------------------------------------------------
-- Exceptions: a holiday, or one day that runs differently.
--
-- session null  -> the whole day
-- is_closed     -> no clinic
-- capacity/times-> override just those, keeping the rest of the pattern
--
-- Known limit (accepted for v1): an exception adjusts a session the weekly
-- pattern already has. It cannot add a session on a weekday the doctor does
-- not normally work -- to open an extra Friday clinic, add Friday to the
-- pattern and remove it afterwards.
-- -----------------------------------------------------------------------------
create table if not exists public.doctor_schedule_exceptions (
  id         bigint generated by default as identity primary key,
  doctor_id  bigint not null references public."Doctors" (id) on delete cascade,
  date       date not null,
  session    text check (session in ('morning', 'evening')),
  is_closed  boolean not null default true,
  start_time time,
  end_time   time,
  capacity   integer check (capacity > 0),
  reason     text,
  created_at timestamptz not null default now(),
  constraint doctor_exception_time_order
    check (start_time is null or end_time is null or end_time > start_time),
  unique (doctor_id, date, session)
);

create index if not exists doctor_schedule_exceptions_lookup_idx
  on public.doctor_schedule_exceptions (doctor_id, date);

-- -----------------------------------------------------------------------------
-- bookings: a booking now belongs to a session, not to a 30-minute slot.
--
-- start_time/end_time are kept as a snapshot of the session window at the time
-- of booking, so a later change to the schedule does not rewrite history.
-- -----------------------------------------------------------------------------
alter table public.bookings
  add column if not exists session text
    check (session is null or session in ('morning', 'evening'));

-- The old index assumed one patient per (doctor, date, start_time). Under the
-- queue model everyone in a session shares the same window, so it would reject
-- the second booking of every session.
drop index if exists public.bookings_no_double_booking;

-- What actually needs preventing now: the same patient taking two places in
-- one session. Capacity is enforced when booking, against doctor_sessions_on.
create unique index if not exists bookings_one_place_per_session
  on public.bookings (doctor_id, patient_id, booked_date, session)
  where status <> 'cancelled';

create index if not exists bookings_session_queue_idx
  on public.bookings (doctor_id, booked_date, session, created_at)
  where status <> 'cancelled';

-- -----------------------------------------------------------------------------
-- What is available for one doctor on one date, after exceptions and bookings.
-- -----------------------------------------------------------------------------
create or replace function public.doctor_sessions_on(p_doctor bigint, p_date date)
returns table (
  session    text,
  start_time time,
  end_time   time,
  capacity   integer,
  booked     bigint,
  remaining  integer
)
language sql
stable
security invoker
set search_path = public
as $$
  with base as (
    select s.session, s.start_time, s.end_time, s.capacity
    from public.doctor_schedule s
    where s.doctor_id = p_doctor
      and s.weekday = extract(dow from p_date)::smallint
      and s.is_active
  ),
  applied as (
    select
      b.session,
      coalesce(ex.start_time, b.start_time) as start_time,
      coalesce(ex.end_time,   b.end_time)   as end_time,
      coalesce(ex.capacity,   b.capacity)   as capacity,
      -- a whole-day exception wins over a per-session one
      coalesce(day_ex.is_closed, ex.is_closed, false) as closed
    from base b
    left join public.doctor_schedule_exceptions ex
      on ex.doctor_id = p_doctor and ex.date = p_date and ex.session = b.session
    left join public.doctor_schedule_exceptions day_ex
      on day_ex.doctor_id = p_doctor and day_ex.date = p_date and day_ex.session is null
  )
  select
    a.session, a.start_time, a.end_time, a.capacity,
    count(bk.id) as booked,
    greatest(a.capacity - count(bk.id), 0)::integer as remaining
  from applied a
  left join public.bookings bk
    on  bk.doctor_id   = p_doctor
    and bk.booked_date = p_date
    and bk.session     = a.session
    and bk.status <> 'cancelled'
  where not a.closed
  group by a.session, a.start_time, a.end_time, a.capacity
  order by a.start_time;
$$;

-- -----------------------------------------------------------------------------
-- Queue position, computed rather than stored.
--
-- Stored numbers would need rewriting for everyone behind a cancellation, and
-- would race when two patients book at the same moment. Computed, a cancelled
-- booking simply drops out and the numbers behind it close up -- which is the
-- promise the patient is shown: your number can improve, never get worse.
-- -----------------------------------------------------------------------------
create or replace view public.booking_queue as
  select
    b.id as booking_id,
    b.doctor_id,
    b.patient_id,
    b.booked_date,
    b.session,
    b.status,
    row_number() over (
      partition by b.doctor_id, b.booked_date, b.session
      order by b.created_at, b.id
    )::integer as queue_number
  from public.bookings b
  where b.status <> 'cancelled';

-- -----------------------------------------------------------------------------
-- Row level security and grants.
--
-- Both, deliberately: policies without grants produce 42501 and are
-- unreachable, which is exactly how the last round broke.
-- -----------------------------------------------------------------------------
alter table public.doctor_schedule            enable row level security;
alter table public.doctor_schedule_exceptions enable row level security;

do $$
declare tbl text;
begin
  foreach tbl in array array['doctor_schedule', 'doctor_schedule_exceptions']
  loop
    -- every signed-in user may read: this is what the app shows as availability
    execute format('drop policy if exists sched_read_all on public.%I;', tbl);
    execute format(
      'create policy sched_read_all on public.%I
         for select to authenticated using (true);', tbl);

    -- only an admin may write, until doctors have accounts of their own;
    -- a doctor-owns-their-schedule policy lands with doctor login
    execute format('drop policy if exists sched_admin_write on public.%I;', tbl);
    execute format(
      'create policy sched_admin_write on public.%I
         for all to authenticated
         using (public.is_admin()) with check (public.is_admin());', tbl);
  end loop;
end $$;

grant select, insert, update, delete
  on public.doctor_schedule, public.doctor_schedule_exceptions
  to authenticated;
grant select on public.doctor_schedule, public.doctor_schedule_exceptions to anon;
grant all on public.doctor_schedule, public.doctor_schedule_exceptions to service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

grant select on public.booking_queue to authenticated, anon, service_role;

revoke execute on function public.doctor_sessions_on(bigint, date) from public;
grant execute on function public.doctor_sessions_on(bigint, date)
  to anon, authenticated, service_role;
