-- =============================================================================
-- Banners for the patient app's home screen, managed from the admin panel.
--
-- The home screen carried a search bar that did nothing for months; the banner
-- replacing it must not become the same thing. So it is content, not code: rows
-- in a table and files in a bucket, changed from the admin panel without a new
-- build of the app.
-- =============================================================================

create table if not exists public.banners (
  id         bigint generated by default as identity primary key,
  image_url  text not null,
  -- Shown over the image. Optional: a banner may be all picture.
  title      text,
  subtitle   text,
  -- Lower first. Ties fall back to id, so the order is always total.
  sort_order integer not null default 0,
  is_active  boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists banners_active_order_idx
  on public.banners (sort_order, id) where is_active;

alter table public.banners enable row level security;

-- A patient sees the active ones. An admin sees all of them, including the
-- ones they have switched off, or they could not switch them back on.
drop policy if exists banners_read on public.banners;
create policy banners_read on public.banners
  for select to authenticated
  using (is_active or public.is_admin());

drop policy if exists banners_admin_write on public.banners;
create policy banners_admin_write on public.banners
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

grant select, insert, update, delete on public.banners to authenticated;
grant all on public.banners to service_role;
grant usage, select on all sequences in schema public
  to anon, authenticated, service_role;

-- -----------------------------------------------------------------------------
-- The bucket the admin panel uploads into.
--
-- Guarded, because the storage schema is a Supabase thing: without this guard
-- the file cannot be run against a plain PostgreSQL, which is where these
-- migrations are tested.
-- -----------------------------------------------------------------------------
do $$
begin
  if to_regclass('storage.buckets') is null then
    raise notice 'storage schema not present -- skipping bucket setup';
    return;
  end if;

  -- public: the images are shown to every patient, so they are served straight
  -- from the CDN rather than through a signed URL per view.
  insert into storage.buckets (id, name, public)
  values ('banners', 'banners', true)
  on conflict (id) do nothing;

  -- Reading is public by the bucket flag above. Writing is the admin's alone --
  -- an authenticated patient must not be able to put files in the app's own
  -- home screen.
  execute 'drop policy if exists banners_insert_admin on storage.objects';
  execute $p$
    create policy banners_insert_admin on storage.objects
      for insert to authenticated
      with check (bucket_id = 'banners' and public.is_admin())
  $p$;

  execute 'drop policy if exists banners_update_admin on storage.objects';
  execute $p$
    create policy banners_update_admin on storage.objects
      for update to authenticated
      using (bucket_id = 'banners' and public.is_admin())
      with check (bucket_id = 'banners' and public.is_admin())
  $p$;

  execute 'drop policy if exists banners_delete_admin on storage.objects';
  execute $p$
    create policy banners_delete_admin on storage.objects
      for delete to authenticated
      using (bucket_id = 'banners' and public.is_admin())
  $p$;
end $$;
