-- =============================================================================
-- A record of what each patient agreed to, and when.
--
-- Storing health data about someone requires their explicit agreement -- Apple
-- and Google both ask for it, and it is the law in most places this app would
-- run. "Explicit" means two things this schema has to support: the patient
-- actively said yes, and we can still show, later, exactly what they said yes
-- to.
--
-- Hence a row per acceptance rather than a flag on the profile. A flag answers
-- "did they agree"; it cannot answer "to which wording", which is the question
-- that matters the day the wording changes. A new version is a new row, and
-- the old one stays as the record of what was true at the time.
--
-- Nothing may edit or delete a row here. A consent record that can be altered
-- afterwards is not a record of anything.
--
-- Safe to re-run.
-- =============================================================================

create table if not exists public.consents (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  -- What was agreed to. Separate kinds because they change on their own
  -- schedules and a patient may have accepted one version of the terms and a
  -- different version of the health notice.
  kind        text not null check (kind in ('health_data', 'terms', 'privacy')),
  -- The wording's own version, as the app knows it: '1.0', '2026-09', anything
  -- stable. Free text on purpose -- this table must never need a migration to
  -- record a new version.
  version     text not null,
  accepted_at timestamptz not null default now(),

  -- Accepting the same version twice is the same fact, not two of them.
  unique (user_id, kind, version)
);

create index if not exists consents_user_kind_idx
  on public.consents (user_id, kind);

alter table public.consents enable row level security;

-- A patient reads their own. An administrator reads all of them, because the
-- question "did this person agree, and when" is one the clinic may have to
-- answer about somebody.
drop policy if exists consents_select_own on public.consents;
create policy consents_select_own on public.consents
  for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

-- Only for yourself, and only ever your own id -- a consent recorded on
-- somebody else's behalf is worth less than none.
drop policy if exists consents_insert_own on public.consents;
create policy consents_insert_own on public.consents
  for insert to authenticated
  with check (user_id = auth.uid());

-- No update and no delete policy anywhere, deliberately: with row level
-- security on and no policy, both are refused for everyone who goes through
-- the API. The rows leave only with the account they belong to.

grant select, insert on public.consents to authenticated;
grant all on public.consents to service_role;

-- -----------------------------------------------------------------------------
-- Signup records the consent in the same breath as the account.
--
-- The app cannot write the row itself straight after signUp: with email
-- confirmation on there is no session yet, so the insert would go out as `anon`
-- and be refused -- and an account that exists without the consent that was
-- actually given is the one state this feature must not produce. The app sends
-- the version as signup metadata instead, and the trigger that already writes
-- the profile writes this too.
-- -----------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  begin
    insert into public.profiles (id, name, phone, gender, birth_date)
    values (
      new.id,
      coalesce(
        nullif(new.raw_user_meta_data ->> 'name', ''),
        split_part(new.email, '@', 1)
      ),
      nullif(new.raw_user_meta_data ->> 'phone', ''),
      -- profiles.gender has a CHECK; anything else is dropped rather than
      -- allowed to fail the insert.
      case
        when new.raw_user_meta_data ->> 'gender' in ('male', 'female')
        then new.raw_user_meta_data ->> 'gender'
      end,
      -- Same for the date: validated by shape before it is cast, because a
      -- cast that throws here would throw inside signup.
      case
        when new.raw_user_meta_data ->> 'birth_date' ~ '^\d{4}-\d{2}-\d{2}$'
        then (new.raw_user_meta_data ->> 'birth_date')::date
      end
    )
    on conflict (id) do nothing;

  exception when others then
    -- A trigger on auth.users that raises makes the signup itself fail. No
    -- detail on a profile is worth refusing to create the account over, so
    -- fall back to the row this trigger has always written and let the person
    -- fix the rest from the profile screen.
    insert into public.profiles (id, name)
    values (new.id, split_part(new.email, '@', 1))
    on conflict (id) do nothing;
  end;

  -- Separately, and just as carefully: a consent nobody can record is still
  -- not worth failing a signup over. The app asks again on the next launch
  -- when the row is missing, which is the same path every patient who
  -- registered before this migration takes.
  begin
    if nullif(new.raw_user_meta_data ->> 'health_consent_version', '')
       is not null then
      insert into public.consents (user_id, kind, version)
      values (
        new.id,
        'health_data',
        new.raw_user_meta_data ->> 'health_consent_version'
      )
      on conflict (user_id, kind, version) do nothing;
    end if;
  exception when others then
    null;
  end;

  return new;
end;
$$;
