-- =============================================================================
-- Settling the commission: what was invoiced, and what was collected.
--
-- 0026 answers "what is owed this month". Asked again next month it answers
-- the same thing about the same month, forever, whether or not the money ever
-- arrived. Without a record of settling, the owner is left reconciling a
-- growing list against her own memory.
--
-- An invoice here freezes its figures. That is the point of it: the statement
-- is a live reading of the bookings and will move if a fee is corrected or a
-- doctor cancels something after the fact, and a bill that quietly changes
-- after it was sent is not a bill. The rows it was computed from stay where
-- they are; what the invoice keeps is what was claimed, on the day it was
-- claimed.
--
-- Nothing is deleted. A mistake is voided with a reason, and the void stays
-- visible, because "this invoice was withdrawn and why" is exactly the
-- question that gets asked six months later.
--
-- Safe to re-run.
-- =============================================================================

create table if not exists public.commission_invoices (
  id            bigint generated by default as identity primary key,
  doctor_id     bigint not null references public."Doctors" (id) on delete restrict,

  -- Inclusive, and normally a calendar month, but not required to be: a doctor
  -- who joins mid-month gets a part period, and the table should not argue.
  period_start  date not null,
  period_end    date not null,

  -- The claim, as it stood when the invoice was raised.
  bookings      integer not null check (bookings >= 0),
  fees          numeric(12,2) not null check (fees >= 0),
  commission    numeric(12,2) not null check (commission >= 0),

  status        text not null default 'issued'
                  check (status in ('issued', 'paid', 'void')),

  issued_at     timestamptz not null default now(),
  issued_by     uuid references auth.users (id) on delete set null,
  paid_at       timestamptz,
  paid_by       uuid references auth.users (id) on delete set null,
  -- How it was settled, in the owner's own words: a transfer reference, "cash
  -- at the clinic", whatever she needs to find it again.
  paid_note     text,
  void_reason   text,
  voided_at     timestamptz,

  constraint commission_invoice_period_order check (period_end >= period_start),
  -- Paid means there is a date on it, and a date means it is paid. Two columns
  -- that can disagree are two columns that eventually do.
  constraint commission_invoice_paid_consistent
    check ((status = 'paid') = (paid_at is not null)),
  constraint commission_invoice_void_consistent
    check ((status = 'void') = (voided_at is not null))
);

-- One live invoice per doctor per period. A voided one does not block a
-- replacement, which is how a mistake gets corrected.
create unique index if not exists commission_invoice_one_per_period
  on public.commission_invoices (doctor_id, period_start, period_end)
  where status <> 'void';

create index if not exists commission_invoices_doctor_idx
  on public.commission_invoices (doctor_id, period_start desc);

alter table public.commission_invoices enable row level security;

-- The owner reads and writes them all. A doctor reads their own and nothing
-- else: they are entitled to see what they are being billed, and entitled to
-- nothing about anyone else's bill.
drop policy if exists commission_invoices_read on public.commission_invoices;
create policy commission_invoices_read on public.commission_invoices
  for select to authenticated
  using (public.is_admin() or doctor_id = public.current_doctor_id());

-- No insert, update or delete policy: every change goes through the functions
-- below, which is what keeps the figures a snapshot rather than something a
-- client can type.
grant select on public.commission_invoices to authenticated;
grant all on public.commission_invoices to service_role;

-- -----------------------------------------------------------------------------
-- Raising one.
--
-- The figures are computed here, from the same rule as the statement: every
-- booking in the period that was not cancelled, at the rate each was booked
-- under.
-- -----------------------------------------------------------------------------
create or replace function public.issue_commission_invoice(
  p_doctor bigint,
  p_from   date,
  p_to     date
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_bookings   integer;
  v_fees       numeric;
  v_commission numeric;
  v_id         bigint;
begin
  if not public.is_admin() then
    raise exception 'Administrators only'
      using errcode = 'insufficient_privilege', hint = 'not_an_admin';
  end if;

  if p_from is null or p_to is null or p_to < p_from then
    raise exception 'Invalid date range'
      using errcode = 'invalid_parameter_value', hint = 'bad_range';
  end if;

  if not exists (select 1 from public."Doctors" where id = p_doctor) then
    raise exception 'Doctor not found'
      using errcode = 'no_data_found', hint = 'doctor_not_found';
  end if;

  select
    count(*),
    coalesce(sum(p.amount), 0),
    coalesce(sum(p.commission_amount), 0)
  into v_bookings, v_fees, v_commission
  from public.bookings b
  join public.payments p on p.id = b.payment_id
  where b.doctor_id   = p_doctor
    and b.booked_date between p_from and p_to
    and b.status <> 'cancelled';

  -- Nothing to bill is not an error, but it is not an invoice either. An
  -- invoice for zero is a piece of paper that says nothing and still has to be
  -- chased, marked paid and filed.
  if v_commission <= 0 then
    raise exception 'Nothing to invoice for this period'
      using errcode = 'no_data_found', hint = 'nothing_due';
  end if;

  insert into public.commission_invoices
    (doctor_id, period_start, period_end, bookings, fees, commission, issued_by)
  values (p_doctor, p_from, p_to, v_bookings, v_fees, v_commission, auth.uid())
  returning id into v_id;

  return json_build_object(
    'id', v_id,
    'doctorId', p_doctor,
    'bookings', v_bookings,
    'fees', v_fees,
    'commission', v_commission,
    'status', 'issued'
  );
exception
  when unique_violation then
    raise exception 'This period is already invoiced for this doctor'
      using errcode = 'unique_violation', hint = 'already_invoiced';
end;
$$;

revoke execute on function public.issue_commission_invoice(bigint, date, date) from public;
grant execute on function public.issue_commission_invoice(bigint, date, date)
  to authenticated, service_role;

-- -----------------------------------------------------------------------------
-- Marking one collected, and taking one back.
-- -----------------------------------------------------------------------------
create or replace function public.settle_commission_invoice(
  p_invoice bigint,
  p_note    text default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result json;
begin
  if not public.is_admin() then
    raise exception 'Administrators only'
      using errcode = 'insufficient_privilege', hint = 'not_an_admin';
  end if;

  update public.commission_invoices i
     set status    = 'paid',
         paid_at   = now(),
         paid_by   = auth.uid(),
         paid_note = nullif(btrim(coalesce(p_note, '')), '')
   where i.id = p_invoice
     and i.status = 'issued'
  returning json_build_object(
    'id', i.id,
    'status', i.status,
    'paidAt', i.paid_at,
    'commission', i.commission
  ) into v_result;

  if v_result is null then
    -- Either it is not there, or it is already paid or void. Said as one
    -- message on purpose: which of the three it is tells a caller about rows
    -- they may not be entitled to know exist.
    raise exception 'No unpaid invoice with that id'
      using errcode = 'no_data_found', hint = 'not_settleable';
  end if;

  return v_result;
end;
$$;

revoke execute on function public.settle_commission_invoice(bigint, text) from public;
grant execute on function public.settle_commission_invoice(bigint, text)
  to authenticated, service_role;

create or replace function public.void_commission_invoice(
  p_invoice bigint,
  p_reason  text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result json;
begin
  if not public.is_admin() then
    raise exception 'Administrators only'
      using errcode = 'insufficient_privilege', hint = 'not_an_admin';
  end if;

  -- A void with no reason is a row that raises the question it was meant to
  -- answer.
  if nullif(btrim(coalesce(p_reason, '')), '') is null then
    raise exception 'A void needs a reason'
      using errcode = 'invalid_parameter_value', hint = 'reason_required';
  end if;

  update public.commission_invoices i
     set status      = 'void',
         voided_at   = now(),
         void_reason = btrim(p_reason),
         -- A voided invoice was never collected, whatever it said before.
         paid_at     = null,
         paid_by     = null
   where i.id = p_invoice
     and i.status <> 'void'
  returning json_build_object('id', i.id, 'status', i.status) into v_result;

  if v_result is null then
    raise exception 'No invoice with that id to void'
      using errcode = 'no_data_found', hint = 'not_voidable';
  end if;

  return v_result;
end;
$$;

revoke execute on function public.void_commission_invoice(bigint, text) from public;
grant execute on function public.void_commission_invoice(bigint, text)
  to authenticated, service_role;

-- -----------------------------------------------------------------------------
-- The statement says which doctors are already invoiced for the period.
--
-- Same function as 0026 with the invoice joined on: the page that shows what
-- is owed is the page the invoice is raised from, and asking twice invites the
-- two answers to disagree.
-- -----------------------------------------------------------------------------
create or replace function public.admin_commission_statement(
  p_from date,
  p_to   date
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result json;
begin
  if not public.is_admin() then
    raise exception 'Administrators only'
      using errcode = 'insufficient_privilege', hint = 'not_an_admin';
  end if;

  if p_from is null or p_to is null or p_to < p_from then
    raise exception 'Invalid date range'
      using errcode = 'invalid_parameter_value', hint = 'bad_range';
  end if;

  with rows as (
    select
      d.id      as doctor_id,
      d.name    as doctor_name,
      b.status  as booking_status,
      b.cancelled_by,
      d.user_id as doctor_user_id,
      p.amount,
      p.commission_rate,
      p.commission_amount
    from public.bookings b
    join public.payments p   on p.id = b.payment_id
    join public."Doctors" d  on d.id = b.doctor_id
    where b.booked_date between p_from and p_to
  ),
  per_doctor as (
    select
      doctor_id,
      doctor_name,
      count(*) filter (where booking_status <> 'cancelled')          as bookings,
      coalesce(sum(amount) filter (where booking_status <> 'cancelled'), 0) as fees,
      coalesce(sum(commission_amount)
                 filter (where booking_status <> 'cancelled'), 0)    as commission,
      coalesce(sum(amount - coalesce(commission_amount, 0))
                 filter (where booking_status <> 'cancelled'), 0)    as net,
      count(*) filter (where booking_status = 'cancelled')           as cancelled,
      count(*) filter (where booking_status = 'cancelled'
                         and cancelled_by is not null
                         and cancelled_by = doctor_user_id)          as cancelled_by_doctor,
      count(*) filter (where booking_status = 'no_show')             as no_show,
      count(*) filter (where booking_status <> 'cancelled'
                         and commission_rate is null)                as unrated
    from rows
    group by doctor_id, doctor_name, doctor_user_id
  ),
  with_invoice as (
    select
      pd.*,
      inv.id         as invoice_id,
      inv.status     as invoice_status,
      inv.commission as invoiced_commission,
      inv.paid_at    as invoice_paid_at
    from per_doctor pd
    left join public.commission_invoices inv
      on inv.doctor_id    = pd.doctor_id
     and inv.period_start = p_from
     and inv.period_end   = p_to
     and inv.status <> 'void'
  )
  select json_build_object(
    'range', json_build_object('from', p_from, 'to', p_to),
    'totals', json_build_object(
      'doctors',    (select count(*) from with_invoice where bookings > 0),
      'bookings',   coalesce((select sum(bookings) from with_invoice), 0),
      'fees',       coalesce((select sum(fees) from with_invoice), 0),
      'commission', coalesce((select sum(commission) from with_invoice), 0),
      'net',        coalesce((select sum(net) from with_invoice), 0),
      'cancelled',  coalesce((select sum(cancelled) from with_invoice), 0),
      'noShow',     coalesce((select sum(no_show) from with_invoice), 0),
      'unrated',    coalesce((select sum(unrated) from with_invoice), 0),
      -- What has actually been settled for this period, and what has not:
      -- the two numbers the month is closed on.
      'invoiced',   coalesce((select sum(invoiced_commission) from with_invoice
                               where invoice_id is not null), 0),
      'collected',  coalesce((select sum(invoiced_commission) from with_invoice
                               where invoice_status = 'paid'), 0)
    ),
    'rows', coalesce((
      select json_agg(r order by r.commission desc, r."doctorName")
      from (
        select
          doctor_id           as "doctorId",
          doctor_name         as "doctorName",
          bookings,
          fees,
          commission,
          net,
          cancelled,
          cancelled_by_doctor as "cancelledByDoctor",
          no_show             as "noShow",
          unrated,
          invoice_id          as "invoiceId",
          invoice_status      as "invoiceStatus",
          invoiced_commission as "invoicedCommission",
          invoice_paid_at     as "invoicePaidAt"
        from with_invoice
        where bookings > 0 or cancelled > 0
      ) r
    ), '[]'::json)
  )
  into v_result;

  return v_result;
end;
$$;

revoke execute on function public.admin_commission_statement(date, date) from public;
grant execute on function public.admin_commission_statement(date, date)
  to authenticated, service_role;
