-- =============================================================================
-- What to send, to whom, and when.
--
-- 0030 recorded where a message can be delivered. This records the message
-- itself, and it is a queue rather than a direct send for three reasons.
--
-- A booking must not depend on Firebase being reachable. The trigger writes a
-- row inside the same transaction as the booking, which costs nothing and
-- cannot fail on somebody else's outage; if the booking rolls back the message
-- goes with it, which is exactly right and is not true of anything sent over
-- the network from inside a trigger.
--
-- A message that failed to send has to be findable. attempts and last_error
-- are here so that "the reminder never arrived" is a question with an answer.
--
-- And the reminders in the next step need a queue anyway: a message written
-- now and sent tomorrow morning is the same row with a later send_after. One
-- sender drains all of it.
--
-- Safe to re-run.
-- =============================================================================

create table if not exists public.notifications (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,

  -- What produced it. Not shown to anyone; it is how we answer "are the
  -- reminders going out" without reading message text.
  kind        text not null,

  title       text not null,
  body        text not null,

  -- Everything the app needs to open the right screen when the notification is
  -- tapped. Firebase requires every value in a message payload to be a string,
  -- so the sender flattens this; it is stored as jsonb because that is what it
  -- is.
  data        jsonb not null default '{}'::jsonb,

  -- Set by any producer that could run twice over the same fact -- a reminder
  -- sweep, above all. Null means "this can only happen once", and null is
  -- distinct from null in a unique index, so those rows never collide.
  dedupe_key  text unique,

  -- The queue is a schedule as well. Now for an event, tomorrow morning for a
  -- reminder written today.
  send_after  timestamptz not null default now(),

  created_at  timestamptz not null default now(),
  sent_at     timestamptz,
  attempts    integer not null default 0,
  last_error  text
);

-- The sender's only query: what is due and not yet gone. Partial, because the
-- sent rows are the ones that accumulate and they are never scanned again.
create index if not exists notifications_pending_idx
  on public.notifications (send_after)
  where sent_at is null;

create index if not exists notifications_user_idx
  on public.notifications (user_id, created_at desc);

alter table public.notifications enable row level security;

-- Readable by the person it is addressed to, and by nobody else. That is for
-- the in-app list this table will also feed; the sender runs with the service
-- role and does not consult policies.
drop policy if exists notifications_read_own on public.notifications;
create policy notifications_read_own on public.notifications
  for select to authenticated
  using (user_id = auth.uid());

revoke all on public.notifications from anon, authenticated;
grant select on public.notifications to authenticated;

-- -----------------------------------------------------------------------------
-- Writing to the queue.
-- -----------------------------------------------------------------------------

-- A doctor whose account was never created has a null user_id, and a booking
-- whose patient was deleted has a null patient_id. Neither is an error worth
-- failing a booking over, so an absent recipient simply produces no row.
create or replace function public.enqueue_notification(
  p_user       uuid,
  p_kind       text,
  p_title      text,
  p_body       text,
  p_data       jsonb default '{}'::jsonb,
  p_send_after timestamptz default now(),
  p_dedupe_key text default null
) returns void
language sql
security definer
set search_path = public
as $$
  insert into public.notifications
    (user_id, kind, title, body, data, send_after, dedupe_key)
  select p_user, p_kind, p_title, p_body,
         coalesce(p_data, '{}'::jsonb),
         coalesce(p_send_after, now()),
         p_dedupe_key
  where p_user is not null
  on conflict (dedupe_key) do nothing;
$$;

-- -----------------------------------------------------------------------------
-- How an appointment reads in a sentence.
--
-- Built here rather than in the sender so that the queue holds the finished
-- text: what was sent is then a fact on the row, not something re-derived
-- later from a template that has since been edited.
--
-- to_char is used with explicit patterns rather than a locale, because the
-- database's locale is not the patient's and never will be.
-- -----------------------------------------------------------------------------
create or replace function public.format_appointment_when(
  p_date  date,
  p_start time
) returns text
language sql
immutable
as $$
  select to_char(p_date, 'FMDD/FMMM/YYYY')
      || ' في تمام '
      || to_char(p_start, 'FMHH12:MI')
      || case when p_start < time '12:00' then ' صباحًا' else ' مساءً' end;
$$;

-- -----------------------------------------------------------------------------
-- A booking was made: tell the patient it stands, and tell the doctor it
-- exists.
-- -----------------------------------------------------------------------------
create or replace function public.notify_on_booking_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_doctor_name  text;
  v_doctor_user  uuid;
  v_patient_name text;
  v_when         text;
begin
  -- Nothing to announce about a booking that arrives already cancelled.
  if new.status = 'cancelled' then
    return new;
  end if;

  select d.name, d.user_id into v_doctor_name, v_doctor_user
  from public."Doctors" d
  where d.id = new.doctor_id;

  select nullif(trim(p.name), '') into v_patient_name
  from public.profiles p
  where p.id = new.patient_id;

  v_when := public.format_appointment_when(new.booked_date, new.start_time);

  perform public.enqueue_notification(
    new.patient_id,
    'booking_created',
    'تم تأكيد الحجز',
    'موعدك مع ' || coalesce(v_doctor_name, 'الطبيب') || ' يوم ' || v_when || '.',
    jsonb_build_object('booking_id', new.id)
  );

  perform public.enqueue_notification(
    v_doctor_user,
    'booking_created_doctor',
    'حجز جديد',
    coalesce(v_patient_name, 'مريض') || ' — يوم ' || v_when || '.',
    jsonb_build_object('booking_id', new.id)
  );

  return new;
end;
$$;

-- -----------------------------------------------------------------------------
-- A booking was cancelled: tell whoever did not do the cancelling, and make
-- sure no reminder for it is still waiting in the queue.
--
-- That second part is the whole reason this runs on cancellation at all. A
-- reminder for an appointment that is no longer happening is worse than no
-- reminder: it sends someone to a clinic.
-- -----------------------------------------------------------------------------
create or replace function public.notify_on_booking_cancelled()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_doctor_name  text;
  v_doctor_user  uuid;
  v_patient_name text;
  v_when         text;
begin
  if new.status <> 'cancelled' or old.status = 'cancelled' then
    return new;
  end if;

  delete from public.notifications
  where sent_at is null
    and kind in ('reminder_day', 'reminder_hour')
    and (data ->> 'booking_id') = new.id::text;

  select d.name, d.user_id into v_doctor_name, v_doctor_user
  from public."Doctors" d
  where d.id = new.doctor_id;

  select nullif(trim(p.name), '') into v_patient_name
  from public.profiles p
  where p.id = new.patient_id;

  v_when := public.format_appointment_when(new.booked_date, new.start_time);

  -- "is distinct from" rather than "<>": a cancellation with no recorded
  -- author tells both sides, which is the safe way round.
  if new.cancelled_by is distinct from new.patient_id then
    perform public.enqueue_notification(
      new.patient_id,
      'booking_cancelled',
      'أُلغي الموعد',
      'موعدك مع ' || coalesce(v_doctor_name, 'الطبيب') || ' يوم ' || v_when
        || ' لم يعد قائمًا.',
      jsonb_build_object('booking_id', new.id)
    );
  end if;

  if new.cancelled_by is distinct from v_doctor_user then
    perform public.enqueue_notification(
      v_doctor_user,
      'booking_cancelled_doctor',
      'أُلغي حجز',
      coalesce(v_patient_name, 'مريض') || ' — يوم ' || v_when || '.',
      jsonb_build_object('booking_id', new.id)
    );
  end if;

  return new;
end;
$$;

drop trigger if exists booking_created_notifies on public.bookings;
create trigger booking_created_notifies
  after insert on public.bookings
  for each row execute function public.notify_on_booking_created();

drop trigger if exists booking_cancelled_notifies on public.bookings;
create trigger booking_cancelled_notifies
  after update of status on public.bookings
  for each row execute function public.notify_on_booking_cancelled();

revoke all on function public.enqueue_notification(uuid, text, text, text, jsonb, timestamptz, text) from public;
revoke all on function public.notify_on_booking_created() from public;
revoke all on function public.notify_on_booking_cancelled() from public;

-- -----------------------------------------------------------------------------
-- The sender's side.
--
-- Claiming is an update rather than a select so that two senders running at
-- once -- a scheduled one and a retried one, say -- cannot both pick up the
-- same message. "for update skip locked" hands the second caller the rows the
-- first did not take, instead of making it wait.
--
-- The attempt is counted at the moment it is handed out, not afterwards. A
-- message whose sender crashed mid-flight has to age out of the queue on its
-- own; a counter that only increases on a recorded failure would leave it
-- being retried for ever.
-- -----------------------------------------------------------------------------
create or replace function public.claim_due_notifications(
  p_limit integer default 100
) returns setof public.notifications
language sql
security definer
set search_path = public
as $$
  update public.notifications n
     set attempts = n.attempts + 1
   where n.id in (
     select d.id
     from public.notifications d
     where d.sent_at is null
       and d.send_after <= now()
       and d.attempts < 5
     order by d.send_after
     limit greatest(1, least(coalesce(p_limit, 100), 500))
     for update skip locked
   )
  returning n.*;
$$;

create or replace function public.mark_notification_sent(p_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update public.notifications
     set sent_at = now(), last_error = null
   where id = p_id;
$$;

-- Kept even when the message has run out of attempts, because the row is the
-- only record of why nothing arrived.
create or replace function public.mark_notification_failed(
  p_id    bigint,
  p_error text
) returns void
language sql
security definer
set search_path = public
as $$
  update public.notifications
     set last_error = left(coalesce(p_error, 'unknown'), 500)
   where id = p_id;
$$;

revoke all on function public.claim_due_notifications(integer) from public;
revoke all on function public.mark_notification_sent(bigint) from public;
revoke all on function public.mark_notification_failed(bigint, text) from public;
grant execute on function public.claim_due_notifications(integer) to service_role;
grant execute on function public.mark_notification_sent(bigint) to service_role;
grant execute on function public.mark_notification_failed(bigint, text) to service_role;

-- The sender reads the queue's recipients' devices and deletes the ones
-- Firebase says no longer exist. 0030 revoked the table from anon and
-- authenticated but said nothing about the service role; said explicitly here
-- rather than left to whatever default privileges happen to be in force.
grant select, delete on public.device_tokens to service_role;
