-- =============================================================================
-- The rating a patient sees, from patients who were actually there.
--
-- `Doctors.rating` has been a plain column since the base schema: default 0,
-- constrained to 0..5, and written by nothing anywhere in the system. The
-- patient app draws it on the search card and again on the doctor's page, so
-- every patient choosing a doctor has been choosing on a number nobody gave.
--
-- A review here is tied to one booking. That is what keeps it honest: there is
-- no way to leave one without having held an appointment with that doctor, the
-- appointment has to have happened, and a second review for the same visit
-- replaces the first rather than stacking. Nothing is anonymous to the
-- database and nothing carries a surname on the screen.
--
-- The doctor's rating is not stored by whoever happens to write last. It is
-- recomputed from the reviews every time one lands, so the number on the card
-- and the reviews behind it can never tell two different stories.
--
-- Safe to re-run.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- How many gave it, beside what they gave.
--
-- 4.9 from two people and 4.4 from three hundred are not the same claim, and a
-- rating shown without its count invites the reader to assume the second.
-- -----------------------------------------------------------------------------
alter table public."Doctors"
  add column if not exists ratings_count integer not null default 0
    check (ratings_count >= 0);

comment on column public."Doctors".rating is
  'Recomputed from doctor_reviews. Never written directly.';
comment on column public."Doctors".ratings_count is
  'How many reviews the average is drawn from. Recomputed with it.';

-- -----------------------------------------------------------------------------
-- The reviews.
-- -----------------------------------------------------------------------------
create table if not exists public.doctor_reviews (
  id         bigint generated by default as identity primary key,

  -- One visit, one review. The unique constraint is the whole integrity story:
  -- a review cannot exist without an appointment behind it, and an appointment
  -- cannot carry two.
  booking_id bigint not null unique references public.bookings (id) on delete cascade,

  -- Denormalised from the booking on purpose: every read of a doctor's reviews
  -- filters by doctor, and the booking is not otherwise needed to answer that.
  doctor_id  bigint not null references public."Doctors" (id) on delete cascade,
  patient_id uuid   not null references public.profiles (id) on delete cascade,

  stars      smallint not null check (stars between 1 and 5),
  -- Optional. A star with nothing after it is still an answer.
  comment    text check (comment is null or length(btrim(comment)) <= 1000),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists doctor_reviews_doctor_idx
  on public.doctor_reviews (doctor_id, created_at desc);
create index if not exists doctor_reviews_patient_idx
  on public.doctor_reviews (patient_id);

alter table public.doctor_reviews enable row level security;

-- Reading: your own, yours as the doctor reviewed, or the owner's. Everybody
-- else reads the view below, which carries no account ids.
drop policy if exists doctor_reviews_read on public.doctor_reviews;
create policy doctor_reviews_read on public.doctor_reviews
  for select to authenticated
  using (
    public.is_admin()
    or patient_id = auth.uid()
    or doctor_id  = public.current_doctor_id()
  );

-- No insert or update policy. Writing goes through rate_booking below, which
-- is the only thing that can check the appointment happened.
revoke all on public.doctor_reviews from anon;
grant select on public.doctor_reviews to authenticated;
grant all    on public.doctor_reviews to service_role;

-- -----------------------------------------------------------------------------
-- Keeping the average honest.
--
-- Recomputed from the rows rather than adjusted in place: an average nudged by
-- each change drifts from the thing it averages, and the drift is invisible
-- until someone counts by hand.
-- -----------------------------------------------------------------------------
create or replace function public.refresh_doctor_rating(p_doctor bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update public."Doctors" d
     set rating = coalesce((
           select round(avg(r.stars)::numeric, 2)
             from public.doctor_reviews r where r.doctor_id = p_doctor
         ), 0),
         ratings_count = (
           select count(*) from public.doctor_reviews r where r.doctor_id = p_doctor
         ),
         updated_at = now()
   where d.id = p_doctor;
$$;

create or replace function public.doctor_reviews_changed()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    perform public.refresh_doctor_rating(old.doctor_id);
    return old;
  end if;

  perform public.refresh_doctor_rating(new.doctor_id);
  -- A review moved between doctors is not a thing that happens, but if it ever
  -- did, the doctor it left would keep a rating it no longer earns.
  if tg_op = 'UPDATE' and old.doctor_id <> new.doctor_id then
    perform public.refresh_doctor_rating(old.doctor_id);
  end if;
  return new;
end;
$$;

drop trigger if exists doctor_reviews_refresh_rating on public.doctor_reviews;
create trigger doctor_reviews_refresh_rating
  after insert or update or delete on public.doctor_reviews
  for each row execute function public.doctor_reviews_changed();

-- -----------------------------------------------------------------------------
-- Leaving one.
-- -----------------------------------------------------------------------------
create or replace function public.rate_booking(
  p_booking bigint,
  p_stars   integer,
  p_comment text default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_booking public.bookings%rowtype;
  v_comment text := nullif(btrim(coalesce(p_comment, '')), '');
  v_id      bigint;
begin
  if p_stars is null or p_stars < 1 or p_stars > 5 then
    raise exception 'A rating is one to five stars'
      using errcode = 'invalid_parameter_value', hint = 'invalid_stars';
  end if;

  if v_comment is not null and length(v_comment) > 1000 then
    raise exception 'That note is too long'
      using errcode = 'invalid_parameter_value', hint = 'comment_too_long';
  end if;

  -- Scoped to the caller in the lookup itself, so somebody else's booking and
  -- a booking that does not exist come back as the same answer.
  select * into v_booking
    from public.bookings
   where id = p_booking and patient_id = auth.uid();

  if not found then
    raise exception 'Booking not found'
      using errcode = 'no_data_found', hint = 'booking_not_found';
  end if;

  if v_booking.status = 'cancelled' then
    raise exception 'That appointment was cancelled'
      using errcode = 'check_violation', hint = 'cancelled_not_rateable';
  end if;

  if v_booking.status = 'no_show' then
    raise exception 'That appointment was not attended'
      using errcode = 'check_violation', hint = 'absent_not_rateable';
  end if;

  -- Before the appointment there is nothing to review. The start is the line
  -- rather than the end, so a patient who has been seen can say so on the way
  -- out instead of waiting for a window they were given to finish.
  if public.appointment_starts_at(v_booking.booked_date, v_booking.start_time) > now() then
    raise exception 'That appointment has not happened yet'
      using errcode = 'check_violation', hint = 'appointment_not_yet';
  end if;

  insert into public.doctor_reviews (booking_id, doctor_id, patient_id, stars, comment)
  values (p_booking, v_booking.doctor_id, auth.uid(), p_stars::smallint, v_comment)
  on conflict (booking_id) do update
    set stars      = excluded.stars,
        comment    = excluded.comment,
        updated_at = now()
  returning id into v_id;

  return json_build_object(
    'id', v_id,
    'bookingId', p_booking,
    'doctorId', v_booking.doctor_id,
    'stars', p_stars,
    'comment', v_comment
  );
end;
$$;

revoke execute on function public.rate_booking(bigint, integer, text) from public;
grant execute on function public.rate_booking(bigint, integer, text) to authenticated;

-- -----------------------------------------------------------------------------
-- Reading them, as a patient choosing a doctor.
--
-- A first name and nothing else. The reviews are there to help somebody
-- choose, not to tell the clinic's waiting room who said what.
-- -----------------------------------------------------------------------------
create or replace view public.doctor_reviews_public as
  select
    r.id,
    r.doctor_id,
    r.stars,
    r.comment,
    r.created_at,
    split_part(btrim(coalesce(p.name, '')), ' ', 1) as reviewer_name
  from public.doctor_reviews r
  left join public.profiles p on p.id = r.patient_id;

comment on view public.doctor_reviews_public is
  'Reviews as a patient browsing may see them: the stars, the note, and a first name.';

alter view public.doctor_reviews_public set (security_invoker = false);
grant select on public.doctor_reviews_public to authenticated;

-- -----------------------------------------------------------------------------
-- The count, beside the average the app already shows.
-- -----------------------------------------------------------------------------
create or replace view public.doctors_public as
  select
    id,
    name,
    title,
    specialization,
    specialty_id,
    clinic_id,
    image,
    location,
    rating,
    consultation_fee,
    waiting_time,
    bio,
    status,
    -- Appended rather than slotted in beside `rating`: `create or replace view`
    -- may add columns at the end and may not renumber the ones already there,
    -- and a view that has to be dropped to gain a column is a view that takes
    -- its grants and its dependants down with it on every change.
    ratings_count
  from public."Doctors";

alter view public.doctors_public set (security_invoker = false);
grant select on public.doctors_public to authenticated;

-- -----------------------------------------------------------------------------
-- Whatever ratings are sitting in the column now were never earned.
--
-- Nothing has ever written one, so anything other than 0 arrived by hand, and
-- a number with no review behind it is exactly what this migration exists to
-- end. Recomputed for every doctor, which sets each to the truth: 0 until
-- somebody reviews them.
-- -----------------------------------------------------------------------------
do $$
declare d bigint;
begin
  for d in select id from public."Doctors" loop
    perform public.refresh_doctor_rating(d);
  end loop;
end $$;
